package org.sicdlab.entrepreneur.beans;
// Generated 2015-7-27 16:33:46 by Hibernate Tools 4.3.1

import java.util.Date;

/**
 * Announcement generated by hbm2java
 */
public class Announcement implements java.io.Serializable {

	private String id;
	private String title;
	private String content;
	private Date publishTime;

	public Announcement() {
	}

	public Announcement(String id, String title, Date publishTime) {
		this.id = id;
		this.title = title;
		this.publishTime = publishTime;
	}

	public Announcement(String id, String title, String content, Date publishTime) {
		this.id = id;
		this.title = title;
		this.content = content;
		this.publishTime = publishTime;
	}

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public String getContent() {
		return this.content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	public Date getPublishTime() {
		return this.publishTime;
	}

	public void setPublishTime(Date publishTime) {
		this.publishTime = publishTime;
	}

}
