package org.sicdlab.entrepreneur.beans;
// Generated 2015-7-27 16:33:46 by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Authority generated by hbm2java
 */
public class Authority implements java.io.Serializable {

	private String id;
	private String name;
	private String description;
	private String signature;
	private Date updateTime;
	private String parentAction;
	private Set roleAuthorities = new HashSet(0);

	public Authority() {
	}

	public Authority(String id, String name, String signature, Date updateTime, String parentAction) {
		this.id = id;
		this.name = name;
		this.signature = signature;
		this.updateTime = updateTime;
		this.parentAction = parentAction;
	}

	public Authority(String id, String name, String description, String signature, Date updateTime, String parentAction,
			Set roleAuthorities) {
		this.id = id;
		this.name = name;
		this.description = description;
		this.signature = signature;
		this.updateTime = updateTime;
		this.parentAction = parentAction;
		this.roleAuthorities = roleAuthorities;
	}

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public String getSignature() {
		return this.signature;
	}

	public void setSignature(String signature) {
		this.signature = signature;
	}

	public Date getUpdateTime() {
		return this.updateTime;
	}

	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	public String getParentAction() {
		return this.parentAction;
	}

	public void setParentAction(String parentAction) {
		this.parentAction = parentAction;
	}

	public Set getRoleAuthorities() {
		return this.roleAuthorities;
	}

	public void setRoleAuthorities(Set roleAuthorities) {
		this.roleAuthorities = roleAuthorities;
	}

}
