package org.sicdlab.entrepreneur.beans;
// Generated 2015-8-5 16:28:47 by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * Authority generated by hbm2java
 */
@Entity
@Table(name = "authority", catalog = "entrepreneur_2015", uniqueConstraints = @UniqueConstraint(columnNames = "name") )
public class Authority implements java.io.Serializable {

	private String id;
	private String name;
	private String description;
	private String signature;
	private Date updateTime;
	private String parentAction;
	private Set roleAuthorities = new HashSet(0);

	public Authority() {
	}

	public Authority(String id, String name, String signature, Date updateTime, String parentAction) {
		this.id = id;
		this.name = name;
		this.signature = signature;
		this.updateTime = updateTime;
		this.parentAction = parentAction;
	}

	public Authority(String id, String name, String description, String signature, Date updateTime, String parentAction, Set roleAuthorities) {
		this.id = id;
		this.name = name;
		this.description = description;
		this.signature = signature;
		this.updateTime = updateTime;
		this.parentAction = parentAction;
		this.roleAuthorities = roleAuthorities;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false, length = 32)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@Column(name = "name", unique = true, nullable = false, length = 50)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "description", length = 500)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "signature", nullable = false, length = 200)
	public String getSignature() {
		return this.signature;
	}

	public void setSignature(String signature) {
		this.signature = signature;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "update_time", nullable = false, length = 19)
	public Date getUpdateTime() {
		return this.updateTime;
	}

	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	@Column(name = "parent_action", nullable = false, length = 50)
	public String getParentAction() {
		return this.parentAction;
	}

	public void setParentAction(String parentAction) {
		this.parentAction = parentAction;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "authority")
	public Set getRoleAuthorities() {
		return this.roleAuthorities;
	}

	public void setRoleAuthorities(Set roleAuthorities) {
		this.roleAuthorities = roleAuthorities;
	}

}
