package org.sicdlab.entrepreneur.beans;
// Generated 2015-7-27 16:33:46 by Hibernate Tools 4.3.1

/**
 * DataDictionary generated by hbm2java
 */
public class DataDictionary implements java.io.Serializable {

	private String id;
	private String ddkey;
	private String ddvalue;

	public DataDictionary() {
	}

	public DataDictionary(String id, String ddkey, String ddvalue) {
		this.id = id;
		this.ddkey = ddkey;
		this.ddvalue = ddvalue;
	}

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getDdkey() {
		return this.ddkey;
	}

	public void setDdkey(String ddkey) {
		this.ddkey = ddkey;
	}

	public String getDdvalue() {
		return this.ddvalue;
	}

	public void setDdvalue(String ddvalue) {
		this.ddvalue = ddvalue;
	}

}
