package org.sicdlab.entrepreneur.beans;
// Generated 2015-8-5 16:28:47 by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * DataDictionary generated by hbm2java
 */
@Entity
@Table(name = "data_dictionary", catalog = "entrepreneur_2015")
public class DataDictionary implements java.io.Serializable {

	private String id;
	private String ddkey;
	private String ddvalue;

	public DataDictionary() {
	}

	public DataDictionary(String id, String ddkey, String ddvalue) {
		this.id = id;
		this.ddkey = ddkey;
		this.ddvalue = ddvalue;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false, length = 32)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@Column(name = "ddkey", nullable = false, length = 50)
	public String getDdkey() {
		return this.ddkey;
	}

	public void setDdkey(String ddkey) {
		this.ddkey = ddkey;
	}

	@Column(name = "ddvalue", nullable = false, length = 500)
	public String getDdvalue() {
		return this.ddvalue;
	}

	public void setDdvalue(String ddvalue) {
		this.ddvalue = ddvalue;
	}

}
