package org.sicdlab.entrepreneur.beans;
// Generated 2015-7-27 16:33:46 by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

/**
 * Entrepreneur generated by hbm2java
 */
public class Entrepreneur implements java.io.Serializable {

	private String id;
	private User user;
	private String degree;
	private String major;
	private String experience;
	private String resumePath;
	private Set projectEntrepreneurs = new HashSet(0);

	public Entrepreneur() {
	}

	public Entrepreneur(User user) {
		this.user = user;
	}

	public Entrepreneur(User user, String degree, String major, String experience, String resumePath,
			Set projectEntrepreneurs) {
		this.user = user;
		this.degree = degree;
		this.major = major;
		this.experience = experience;
		this.resumePath = resumePath;
		this.projectEntrepreneurs = projectEntrepreneurs;
	}

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	public String getDegree() {
		return this.degree;
	}

	public void setDegree(String degree) {
		this.degree = degree;
	}

	public String getMajor() {
		return this.major;
	}

	public void setMajor(String major) {
		this.major = major;
	}

	public String getExperience() {
		return this.experience;
	}

	public void setExperience(String experience) {
		this.experience = experience;
	}

	public String getResumePath() {
		return this.resumePath;
	}

	public void setResumePath(String resumePath) {
		this.resumePath = resumePath;
	}

	public Set getProjectEntrepreneurs() {
		return this.projectEntrepreneurs;
	}

	public void setProjectEntrepreneurs(Set projectEntrepreneurs) {
		this.projectEntrepreneurs = projectEntrepreneurs;
	}

}
