package org.sicdlab.entrepreneur.beans;
// Generated 2015-8-5 16:28:47 by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * EnvironmentFactor generated by hbm2java
 */
@Entity
@Table(name = "environment_factor", catalog = "entrepreneur_2015")
public class EnvironmentFactor implements java.io.Serializable {

	private String environmentFactorId;
	private float policySupport;
	private float resourceSupportDegree;
	private float economyBoomDegree;
	private float totalScore;
	private String comment;
	private Set projectIndexes = new HashSet(0);

	public EnvironmentFactor() {
	}

	public EnvironmentFactor(String environmentFactorId, float policySupport, float resourceSupportDegree, float economyBoomDegree, float totalScore) {
		this.environmentFactorId = environmentFactorId;
		this.policySupport = policySupport;
		this.resourceSupportDegree = resourceSupportDegree;
		this.economyBoomDegree = economyBoomDegree;
		this.totalScore = totalScore;
	}

	public EnvironmentFactor(String environmentFactorId, float policySupport, float resourceSupportDegree, float economyBoomDegree, float totalScore, String comment,
			Set projectIndexes) {
		this.environmentFactorId = environmentFactorId;
		this.policySupport = policySupport;
		this.resourceSupportDegree = resourceSupportDegree;
		this.economyBoomDegree = economyBoomDegree;
		this.totalScore = totalScore;
		this.comment = comment;
		this.projectIndexes = projectIndexes;
	}

	@Id

	@Column(name = "ENVIRONMENT_FACTOR_ID", unique = true, nullable = false, length = 32)
	public String getEnvironmentFactorId() {
		return this.environmentFactorId;
	}

	public void setEnvironmentFactorId(String environmentFactorId) {
		this.environmentFactorId = environmentFactorId;
	}

	@Column(name = "POLICY_SUPPORT", nullable = false, precision = 10)
	public float getPolicySupport() {
		return this.policySupport;
	}

	public void setPolicySupport(float policySupport) {
		this.policySupport = policySupport;
	}

	@Column(name = "RESOURCE_SUPPORT_DEGREE", nullable = false, precision = 10)
	public float getResourceSupportDegree() {
		return this.resourceSupportDegree;
	}

	public void setResourceSupportDegree(float resourceSupportDegree) {
		this.resourceSupportDegree = resourceSupportDegree;
	}

	@Column(name = "ECONOMY_BOOM_DEGREE", nullable = false, precision = 10)
	public float getEconomyBoomDegree() {
		return this.economyBoomDegree;
	}

	public void setEconomyBoomDegree(float economyBoomDegree) {
		this.economyBoomDegree = economyBoomDegree;
	}

	@Column(name = "TOTAL_SCORE", nullable = false, precision = 10)
	public float getTotalScore() {
		return this.totalScore;
	}

	public void setTotalScore(float totalScore) {
		this.totalScore = totalScore;
	}

	@Column(name = "COMMENT", length = 65535)
	public String getComment() {
		return this.comment;
	}

	public void setComment(String comment) {
		this.comment = comment;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "environmentFactor")
	public Set getProjectIndexes() {
		return this.projectIndexes;
	}

	public void setProjectIndexes(Set projectIndexes) {
		this.projectIndexes = projectIndexes;
	}

}
