package org.sicdlab.entrepreneur.beans;
// Generated 2015-8-5 16:28:47 by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * FinanceFactor generated by hbm2java
 */
@Entity
@Table(name = "finance_factor", catalog = "entrepreneur_2015")
public class FinanceFactor implements java.io.Serializable {

	private String financeFactorId;
	private float returnOnInvestment;
	private float financeRecoverTimeAndBarrier;
	private float financePlanRationality;
	private float retureOnInvestment;
	private float totalScore;
	private String comment;
	private Set projectIndexes = new HashSet(0);

	public FinanceFactor() {
	}

	public FinanceFactor(String financeFactorId, float returnOnInvestment, float financeRecoverTimeAndBarrier, float financePlanRationality, float retureOnInvestment,
			float totalScore) {
		this.financeFactorId = financeFactorId;
		this.returnOnInvestment = returnOnInvestment;
		this.financeRecoverTimeAndBarrier = financeRecoverTimeAndBarrier;
		this.financePlanRationality = financePlanRationality;
		this.retureOnInvestment = retureOnInvestment;
		this.totalScore = totalScore;
	}

	public FinanceFactor(String financeFactorId, float returnOnInvestment, float financeRecoverTimeAndBarrier, float financePlanRationality, float retureOnInvestment,
			float totalScore, String comment, Set projectIndexes) {
		this.financeFactorId = financeFactorId;
		this.returnOnInvestment = returnOnInvestment;
		this.financeRecoverTimeAndBarrier = financeRecoverTimeAndBarrier;
		this.financePlanRationality = financePlanRationality;
		this.retureOnInvestment = retureOnInvestment;
		this.totalScore = totalScore;
		this.comment = comment;
		this.projectIndexes = projectIndexes;
	}

	@Id

	@Column(name = "FINANCE_FACTOR_ID", unique = true, nullable = false, length = 32)
	public String getFinanceFactorId() {
		return this.financeFactorId;
	}

	public void setFinanceFactorId(String financeFactorId) {
		this.financeFactorId = financeFactorId;
	}

	@Column(name = "RETURN_ON_INVESTMENT", nullable = false, precision = 10)
	public float getReturnOnInvestment() {
		return this.returnOnInvestment;
	}

	public void setReturnOnInvestment(float returnOnInvestment) {
		this.returnOnInvestment = returnOnInvestment;
	}

	@Column(name = "FINANCE_RECOVER_TIME_AND_BARRIER", nullable = false, precision = 10)
	public float getFinanceRecoverTimeAndBarrier() {
		return this.financeRecoverTimeAndBarrier;
	}

	public void setFinanceRecoverTimeAndBarrier(float financeRecoverTimeAndBarrier) {
		this.financeRecoverTimeAndBarrier = financeRecoverTimeAndBarrier;
	}

	@Column(name = "FINANCE_PLAN_RATIONALITY", nullable = false, precision = 10)
	public float getFinancePlanRationality() {
		return this.financePlanRationality;
	}

	public void setFinancePlanRationality(float financePlanRationality) {
		this.financePlanRationality = financePlanRationality;
	}

	@Column(name = "RETURE_ON_INVESTMENT", nullable = false, precision = 10)
	public float getRetureOnInvestment() {
		return this.retureOnInvestment;
	}

	public void setRetureOnInvestment(float retureOnInvestment) {
		this.retureOnInvestment = retureOnInvestment;
	}

	@Column(name = "TOTAL_SCORE", nullable = false, precision = 10)
	public float getTotalScore() {
		return this.totalScore;
	}

	public void setTotalScore(float totalScore) {
		this.totalScore = totalScore;
	}

	@Column(name = "COMMENT", length = 65535)
	public String getComment() {
		return this.comment;
	}

	public void setComment(String comment) {
		this.comment = comment;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "financeFactor")
	public Set getProjectIndexes() {
		return this.projectIndexes;
	}

	public void setProjectIndexes(Set projectIndexes) {
		this.projectIndexes = projectIndexes;
	}

}
