package org.sicdlab.entrepreneur.beans;
// Generated 2015-7-27 16:33:46 by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

/**
 * FinanceFactor generated by hbm2java
 */
public class FinanceFactor implements java.io.Serializable {

	private String financeFactorId;
	private float returnOnInvestment;
	private float financeRecoverTimeAndBarrier;
	private float financePlanRationality;
	private float retureOnInvestment;
	private float totalScore;
	private String comment;
	private Set projectIndexes = new HashSet(0);

	public FinanceFactor() {
	}

	public FinanceFactor(String financeFactorId, float returnOnInvestment, float financeRecoverTimeAndBarrier,
			float financePlanRationality, float retureOnInvestment, float totalScore) {
		this.financeFactorId = financeFactorId;
		this.returnOnInvestment = returnOnInvestment;
		this.financeRecoverTimeAndBarrier = financeRecoverTimeAndBarrier;
		this.financePlanRationality = financePlanRationality;
		this.retureOnInvestment = retureOnInvestment;
		this.totalScore = totalScore;
	}

	public FinanceFactor(String financeFactorId, float returnOnInvestment, float financeRecoverTimeAndBarrier,
			float financePlanRationality, float retureOnInvestment, float totalScore, String comment,
			Set projectIndexes) {
		this.financeFactorId = financeFactorId;
		this.returnOnInvestment = returnOnInvestment;
		this.financeRecoverTimeAndBarrier = financeRecoverTimeAndBarrier;
		this.financePlanRationality = financePlanRationality;
		this.retureOnInvestment = retureOnInvestment;
		this.totalScore = totalScore;
		this.comment = comment;
		this.projectIndexes = projectIndexes;
	}

	public String getFinanceFactorId() {
		return this.financeFactorId;
	}

	public void setFinanceFactorId(String financeFactorId) {
		this.financeFactorId = financeFactorId;
	}

	public float getReturnOnInvestment() {
		return this.returnOnInvestment;
	}

	public void setReturnOnInvestment(float returnOnInvestment) {
		this.returnOnInvestment = returnOnInvestment;
	}

	public float getFinanceRecoverTimeAndBarrier() {
		return this.financeRecoverTimeAndBarrier;
	}

	public void setFinanceRecoverTimeAndBarrier(float financeRecoverTimeAndBarrier) {
		this.financeRecoverTimeAndBarrier = financeRecoverTimeAndBarrier;
	}

	public float getFinancePlanRationality() {
		return this.financePlanRationality;
	}

	public void setFinancePlanRationality(float financePlanRationality) {
		this.financePlanRationality = financePlanRationality;
	}

	public float getRetureOnInvestment() {
		return this.retureOnInvestment;
	}

	public void setRetureOnInvestment(float retureOnInvestment) {
		this.retureOnInvestment = retureOnInvestment;
	}

	public float getTotalScore() {
		return this.totalScore;
	}

	public void setTotalScore(float totalScore) {
		this.totalScore = totalScore;
	}

	public String getComment() {
		return this.comment;
	}

	public void setComment(String comment) {
		this.comment = comment;
	}

	public Set getProjectIndexes() {
		return this.projectIndexes;
	}

	public void setProjectIndexes(Set projectIndexes) {
		this.projectIndexes = projectIndexes;
	}

}
