package org.sicdlab.entrepreneur.beans;
// Generated 2015-8-5 16:28:47 by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Friend generated by hbm2java
 */
@Entity
@Table(name = "friend", catalog = "entrepreneur_2015")
public class Friend implements java.io.Serializable {

	private String id;
	private User userByFollowerId;
	private User userByFolloweeId;
	private String status;

	public Friend() {
	}

	public Friend(String id, User userByFollowerId, User userByFolloweeId, String status) {
		this.id = id;
		this.userByFollowerId = userByFollowerId;
		this.userByFolloweeId = userByFolloweeId;
		this.status = status;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false, length = 32)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "follower_id", nullable = false)
	public User getUserByFollowerId() {
		return this.userByFollowerId;
	}

	public void setUserByFollowerId(User userByFollowerId) {
		this.userByFollowerId = userByFollowerId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "followee_id", nullable = false)
	public User getUserByFolloweeId() {
		return this.userByFolloweeId;
	}

	public void setUserByFolloweeId(User userByFolloweeId) {
		this.userByFolloweeId = userByFolloweeId;
	}

	@Column(name = "status", nullable = false, length = 50)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

}
