package org.sicdlab.entrepreneur.beans;
// Generated 2015-8-5 16:28:47 by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * FriendlyLink generated by hbm2java
 */
@Entity
@Table(name = "friendly_link", catalog = "entrepreneur_2015")
public class FriendlyLink implements java.io.Serializable {

	private String id;
	private String title;
	private String url;
	private String image;

	public FriendlyLink() {
	}

	public FriendlyLink(String id) {
		this.id = id;
	}

	public FriendlyLink(String id, String title, String url, String image) {
		this.id = id;
		this.title = title;
		this.url = url;
		this.image = image;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false, length = 32)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@Column(name = "title", length = 50)
	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	@Column(name = "url", length = 200)
	public String getUrl() {
		return this.url;
	}

	public void setUrl(String url) {
		this.url = url;
	}

	@Column(name = "image", length = 200)
	public String getImage() {
		return this.image;
	}

	public void setImage(String image) {
		this.image = image;
	}

}
