package org.sicdlab.entrepreneur.beans;
// Generated 2015-7-27 16:33:46 by Hibernate Tools 4.3.1

/**
 * Friend generated by hbm2java
 */
public class Friend implements java.io.Serializable {

	private String id;
	private User userByFollowerId;
	private User userByFolloweeId;
	private String status;

	public Friend() {
	}

	public Friend(String id, User userByFollowerId, User userByFolloweeId, String status) {
		this.id = id;
		this.userByFollowerId = userByFollowerId;
		this.userByFolloweeId = userByFolloweeId;
		this.status = status;
	}

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public User getUserByFollowerId() {
		return this.userByFollowerId;
	}

	public void setUserByFollowerId(User userByFollowerId) {
		this.userByFollowerId = userByFollowerId;
	}

	public User getUserByFolloweeId() {
		return this.userByFolloweeId;
	}

	public void setUserByFolloweeId(User userByFolloweeId) {
		this.userByFolloweeId = userByFolloweeId;
	}

	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

}
