package org.sicdlab.entrepreneur.beans;
// Generated 2015-7-27 16:33:46 by Hibernate Tools 4.3.1

/**
 * FriendlyLink generated by hbm2java
 */
public class FriendlyLink implements java.io.Serializable {

	private String id;
	private String title;
	private String url;
	private String image;

	public FriendlyLink() {
	}

	public FriendlyLink(String id) {
		this.id = id;
	}

	public FriendlyLink(String id, String title, String url, String image) {
		this.id = id;
		this.title = title;
		this.url = url;
		this.image = image;
	}

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public String getUrl() {
		return this.url;
	}

	public void setUrl(String url) {
		this.url = url;
	}

	public String getImage() {
		return this.image;
	}

	public void setImage(String image) {
		this.image = image;
	}

}
