package org.sicdlab.entrepreneur.beans;
// Generated 2015-7-27 16:33:46 by Hibernate Tools 4.3.1

/**
 * Help generated by hbm2java
 */
public class Help implements java.io.Serializable {

	private String id;
	private String helpType;
	private String title;
	private String content;

	public Help() {
	}

	public Help(String id) {
		this.id = id;
	}

	public Help(String id, String helpType, String title, String content) {
		this.id = id;
		this.helpType = helpType;
		this.title = title;
		this.content = content;
	}

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getHelpType() {
		return this.helpType;
	}

	public void setHelpType(String helpType) {
		this.helpType = helpType;
	}

	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public String getContent() {
		return this.content;
	}

	public void setContent(String content) {
		this.content = content;
	}

}
