package org.sicdlab.entrepreneur.beans;
// Generated 2015-8-5 16:28:47 by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Help generated by hbm2java
 */
@Entity
@Table(name = "help", catalog = "entrepreneur_2015")
public class Help implements java.io.Serializable {

	private String id;
	private String helpType;
	private String title;
	private String content;

	public Help() {
	}

	public Help(String id) {
		this.id = id;
	}

	public Help(String id, String helpType, String title, String content) {
		this.id = id;
		this.helpType = helpType;
		this.title = title;
		this.content = content;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false, length = 32)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@Column(name = "help_type", length = 50)
	public String getHelpType() {
		return this.helpType;
	}

	public void setHelpType(String helpType) {
		this.helpType = helpType;
	}

	@Column(name = "title", length = 200)
	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	@Column(name = "content", length = 65535)
	public String getContent() {
		return this.content;
	}

	public void setContent(String content) {
		this.content = content;
	}

}
