package org.sicdlab.entrepreneur.beans;
// Generated 2015-8-5 16:28:47 by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Industry generated by hbm2java
 */
@Entity
@Table(name = "industry", catalog = "entrepreneur_2015", uniqueConstraints = @UniqueConstraint(columnNames = "name") )
public class Industry implements java.io.Serializable {

	private String id;
	private String name;
	private String saturation;
	private String entryBarrier;
	private String maturity;
	private String scale;
	private String future;
	private String description;
	private Set laws = new HashSet(0);
	private Set knowledges = new HashSet(0);
	private Set supplies = new HashSet(0);
	private Set policies = new HashSet(0);
	private Set needs = new HashSet(0);
	private Set projects = new HashSet(0);

	public Industry() {
	}

	public Industry(String id, String name) {
		this.id = id;
		this.name = name;
	}

	public Industry(String id, String name, String saturation, String entryBarrier, String maturity, String scale, String future, String description, Set laws, Set knowledges,
			Set supplies, Set policies, Set needs, Set projects) {
		this.id = id;
		this.name = name;
		this.saturation = saturation;
		this.entryBarrier = entryBarrier;
		this.maturity = maturity;
		this.scale = scale;
		this.future = future;
		this.description = description;
		this.laws = laws;
		this.knowledges = knowledges;
		this.supplies = supplies;
		this.policies = policies;
		this.needs = needs;
		this.projects = projects;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false, length = 32)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@Column(name = "name", unique = true, nullable = false, length = 50)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "saturation", length = 50)
	public String getSaturation() {
		return this.saturation;
	}

	public void setSaturation(String saturation) {
		this.saturation = saturation;
	}

	@Column(name = "entry_barrier", length = 50)
	public String getEntryBarrier() {
		return this.entryBarrier;
	}

	public void setEntryBarrier(String entryBarrier) {
		this.entryBarrier = entryBarrier;
	}

	@Column(name = "maturity", length = 50)
	public String getMaturity() {
		return this.maturity;
	}

	public void setMaturity(String maturity) {
		this.maturity = maturity;
	}

	@Column(name = "scale", length = 50)
	public String getScale() {
		return this.scale;
	}

	public void setScale(String scale) {
		this.scale = scale;
	}

	@Column(name = "future", length = 50)
	public String getFuture() {
		return this.future;
	}

	public void setFuture(String future) {
		this.future = future;
	}

	@Column(name = "description", length = 65535)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "industry")
	public Set getLaws() {
		return this.laws;
	}

	public void setLaws(Set laws) {
		this.laws = laws;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "industry")
	public Set getKnowledges() {
		return this.knowledges;
	}

	public void setKnowledges(Set knowledges) {
		this.knowledges = knowledges;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "industry")
	public Set getSupplies() {
		return this.supplies;
	}

	public void setSupplies(Set supplies) {
		this.supplies = supplies;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "industry")
	public Set getPolicies() {
		return this.policies;
	}

	public void setPolicies(Set policies) {
		this.policies = policies;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "industry")
	public Set getNeeds() {
		return this.needs;
	}

	public void setNeeds(Set needs) {
		this.needs = needs;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "industry")
	public Set getProjects() {
		return this.projects;
	}

	public void setProjects(Set projects) {
		this.projects = projects;
	}

}
