package org.sicdlab.entrepreneur.beans;
// Generated 2015-7-27 16:33:46 by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

/**
 * Institution generated by hbm2java
 */
public class Institution implements java.io.Serializable {

	private String id;
	private User user;
	private String type;
	private String principal;
	private String scale;
	private String service;
	private String fosterIndustry;
	private Set projectInstitutions = new HashSet(0);

	public Institution() {
	}

	public Institution(User user) {
		this.user = user;
	}

	public Institution(User user, String type, String principal, String scale, String service, String fosterIndustry,
			Set projectInstitutions) {
		this.user = user;
		this.type = type;
		this.principal = principal;
		this.scale = scale;
		this.service = service;
		this.fosterIndustry = fosterIndustry;
		this.projectInstitutions = projectInstitutions;
	}

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	public String getPrincipal() {
		return this.principal;
	}

	public void setPrincipal(String principal) {
		this.principal = principal;
	}

	public String getScale() {
		return this.scale;
	}

	public void setScale(String scale) {
		this.scale = scale;
	}

	public String getService() {
		return this.service;
	}

	public void setService(String service) {
		this.service = service;
	}

	public String getFosterIndustry() {
		return this.fosterIndustry;
	}

	public void setFosterIndustry(String fosterIndustry) {
		this.fosterIndustry = fosterIndustry;
	}

	public Set getProjectInstitutions() {
		return this.projectInstitutions;
	}

	public void setProjectInstitutions(Set projectInstitutions) {
		this.projectInstitutions = projectInstitutions;
	}

}
