package org.sicdlab.entrepreneur.beans;
// Generated 2015-8-5 16:28:47 by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * Institution generated by hbm2java
 */
@Entity
@Table(name = "institution", catalog = "entrepreneur_2015")
public class Institution implements java.io.Serializable {

	private String id;
	private User user;
	private String type;
	private String principal;
	private String scale;
	private String service;
	private String fosterIndustry;
	private Set projectInstitutions = new HashSet(0);

	public Institution() {
	}

	public Institution(User user) {
		this.user = user;
	}

	public Institution(User user, String type, String principal, String scale, String service, String fosterIndustry, Set projectInstitutions) {
		this.user = user;
		this.type = type;
		this.principal = principal;
		this.scale = scale;
		this.service = service;
		this.fosterIndustry = fosterIndustry;
		this.projectInstitutions = projectInstitutions;
	}

	@GenericGenerator(name = "generator", strategy = "foreign", parameters = @Parameter(name = "property", value = "user") )
	@Id
	@GeneratedValue(generator = "generator")

	@Column(name = "id", unique = true, nullable = false, length = 32)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@OneToOne(fetch = FetchType.LAZY)
	@PrimaryKeyJoinColumn
	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	@Column(name = "type", length = 50)
	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	@Column(name = "principal", length = 50)
	public String getPrincipal() {
		return this.principal;
	}

	public void setPrincipal(String principal) {
		this.principal = principal;
	}

	@Column(name = "scale", length = 65535)
	public String getScale() {
		return this.scale;
	}

	public void setScale(String scale) {
		this.scale = scale;
	}

	@Column(name = "service", length = 65535)
	public String getService() {
		return this.service;
	}

	public void setService(String service) {
		this.service = service;
	}

	@Column(name = "foster_industry", length = 200)
	public String getFosterIndustry() {
		return this.fosterIndustry;
	}

	public void setFosterIndustry(String fosterIndustry) {
		this.fosterIndustry = fosterIndustry;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "institution")
	public Set getProjectInstitutions() {
		return this.projectInstitutions;
	}

	public void setProjectInstitutions(Set projectInstitutions) {
		this.projectInstitutions = projectInstitutions;
	}

}
