package org.sicdlab.entrepreneur.beans;
// Generated 2015-8-5 16:28:47 by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * KnowledgeLabel generated by hbm2java
 */
@Entity
@Table(name = "knowledge_label", catalog = "entrepreneur_2015")
public class KnowledgeLabel implements java.io.Serializable {

	private String id;
	private Knowledge knowledge;
	private Label label;

	public KnowledgeLabel() {
	}

	public KnowledgeLabel(String id, Knowledge knowledge, Label label) {
		this.id = id;
		this.knowledge = knowledge;
		this.label = label;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false, length = 32)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "knowledge_id", nullable = false)
	public Knowledge getKnowledge() {
		return this.knowledge;
	}

	public void setKnowledge(Knowledge knowledge) {
		this.knowledge = knowledge;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "label_id", nullable = false)
	public Label getLabel() {
		return this.label;
	}

	public void setLabel(Label label) {
		this.label = label;
	}

}
