package org.sicdlab.entrepreneur.beans;
// Generated 2015-7-27 16:33:46 by Hibernate Tools 4.3.1

/**
 * KnowledgeLabel generated by hbm2java
 */
public class KnowledgeLabel implements java.io.Serializable {

	private String id;
	private Knowledge knowledge;
	private Label label;

	public KnowledgeLabel() {
	}

	public KnowledgeLabel(String id, Knowledge knowledge, Label label) {
		this.id = id;
		this.knowledge = knowledge;
		this.label = label;
	}

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public Knowledge getKnowledge() {
		return this.knowledge;
	}

	public void setKnowledge(Knowledge knowledge) {
		this.knowledge = knowledge;
	}

	public Label getLabel() {
		return this.label;
	}

	public void setLabel(Label label) {
		this.label = label;
	}

}
