package org.sicdlab.entrepreneur.beans;
// Generated 2015-8-5 16:28:47 by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Knowledge generated by hbm2java
 */
@Entity
@Table(name = "knowledge", catalog = "entrepreneur_2015")
public class Knowledge implements java.io.Serializable {

	private String id;
	private Industry industry;
	private String title;
	private String content;
	private String type;
	private Date publishTime;
	private String projectStage;
	private String headImage;
	private Set knowledgeLabels = new HashSet(0);

	public Knowledge() {
	}

	public Knowledge(String id) {
		this.id = id;
	}

	public Knowledge(String id, Industry industry, String title, String content, String type, Date publishTime, String projectStage, String headImage, Set knowledgeLabels) {
		this.id = id;
		this.industry = industry;
		this.title = title;
		this.content = content;
		this.type = type;
		this.publishTime = publishTime;
		this.projectStage = projectStage;
		this.headImage = headImage;
		this.knowledgeLabels = knowledgeLabels;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false, length = 32)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "industry_id")
	public Industry getIndustry() {
		return this.industry;
	}

	public void setIndustry(Industry industry) {
		this.industry = industry;
	}

	@Column(name = "title", length = 200)
	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	@Column(name = "content", length = 65535)
	public String getContent() {
		return this.content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	@Column(name = "type", length = 50)
	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "publish_time", length = 19)
	public Date getPublishTime() {
		return this.publishTime;
	}

	public void setPublishTime(Date publishTime) {
		this.publishTime = publishTime;
	}

	@Column(name = "project_stage", length = 50)
	public String getProjectStage() {
		return this.projectStage;
	}

	public void setProjectStage(String projectStage) {
		this.projectStage = projectStage;
	}

	@Column(name = "head_image", length = 200)
	public String getHeadImage() {
		return this.headImage;
	}

	public void setHeadImage(String headImage) {
		this.headImage = headImage;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "knowledge")
	public Set getKnowledgeLabels() {
		return this.knowledgeLabels;
	}

	public void setKnowledgeLabels(Set knowledgeLabels) {
		this.knowledgeLabels = knowledgeLabels;
	}

}
