package org.sicdlab.entrepreneur.beans;
// Generated 2015-7-27 16:33:46 by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Knowledge generated by hbm2java
 */
public class Knowledge implements java.io.Serializable {

	private String id;
	private Industry industry;
	private String title;
	private String content;
	private String type;
	private Date publishTime;
	private String projectStage;
	private Set knowledgeLabels = new HashSet(0);

	public Knowledge() {
	}

	public Knowledge(String id) {
		this.id = id;
	}

	public Knowledge(String id, Industry industry, String title, String content, String type, Date publishTime,
			String projectStage, Set knowledgeLabels) {
		this.id = id;
		this.industry = industry;
		this.title = title;
		this.content = content;
		this.type = type;
		this.publishTime = publishTime;
		this.projectStage = projectStage;
		this.knowledgeLabels = knowledgeLabels;
	}

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public Industry getIndustry() {
		return this.industry;
	}

	public void setIndustry(Industry industry) {
		this.industry = industry;
	}

	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public String getContent() {
		return this.content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	public Date getPublishTime() {
		return this.publishTime;
	}

	public void setPublishTime(Date publishTime) {
		this.publishTime = publishTime;
	}

	public String getProjectStage() {
		return this.projectStage;
	}

	public void setProjectStage(String projectStage) {
		this.projectStage = projectStage;
	}

	public Set getKnowledgeLabels() {
		return this.knowledgeLabels;
	}

	public void setKnowledgeLabels(Set knowledgeLabels) {
		this.knowledgeLabels = knowledgeLabels;
	}

}
