package org.sicdlab.entrepreneur.beans;
// Generated 2015-7-27 16:33:46 by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

/**
 * Label generated by hbm2java
 */
public class Label implements java.io.Serializable {

	private String id;
	private int count;
	private String name;
	private Set knowledgeLabels = new HashSet(0);
	private Set projectLabels = new HashSet(0);
	private Set supplyLabels = new HashSet(0);
	private Set policyLabels = new HashSet(0);
	private Set lawLabels = new HashSet(0);
	private Set needLabels = new HashSet(0);

	public Label() {
	}

	public Label(String id, int count, String name) {
		this.id = id;
		this.count = count;
		this.name = name;
	}

	public Label(String id, int count, String name, Set knowledgeLabels, Set projectLabels, Set supplyLabels,
			Set policyLabels, Set lawLabels, Set needLabels) {
		this.id = id;
		this.count = count;
		this.name = name;
		this.knowledgeLabels = knowledgeLabels;
		this.projectLabels = projectLabels;
		this.supplyLabels = supplyLabels;
		this.policyLabels = policyLabels;
		this.lawLabels = lawLabels;
		this.needLabels = needLabels;
	}

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public int getCount() {
		return this.count;
	}

	public void setCount(int count) {
		this.count = count;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Set getKnowledgeLabels() {
		return this.knowledgeLabels;
	}

	public void setKnowledgeLabels(Set knowledgeLabels) {
		this.knowledgeLabels = knowledgeLabels;
	}

	public Set getProjectLabels() {
		return this.projectLabels;
	}

	public void setProjectLabels(Set projectLabels) {
		this.projectLabels = projectLabels;
	}

	public Set getSupplyLabels() {
		return this.supplyLabels;
	}

	public void setSupplyLabels(Set supplyLabels) {
		this.supplyLabels = supplyLabels;
	}

	public Set getPolicyLabels() {
		return this.policyLabels;
	}

	public void setPolicyLabels(Set policyLabels) {
		this.policyLabels = policyLabels;
	}

	public Set getLawLabels() {
		return this.lawLabels;
	}

	public void setLawLabels(Set lawLabels) {
		this.lawLabels = lawLabels;
	}

	public Set getNeedLabels() {
		return this.needLabels;
	}

	public void setNeedLabels(Set needLabels) {
		this.needLabels = needLabels;
	}

}
