package org.sicdlab.entrepreneur.beans;
// Generated 2015-7-27 16:33:46 by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Law generated by hbm2java
 */
public class Law implements java.io.Serializable {

	private String id;
	private Industry industry;
	private String title;
	private Date publishTime;
	private String content;
	private String type;
	private Integer readCount;
	private String projectStage;
	private Set lawLabels = new HashSet(0);

	public Law() {
	}

	public Law(String id, String title, Date publishTime, String content, String type) {
		this.id = id;
		this.title = title;
		this.publishTime = publishTime;
		this.content = content;
		this.type = type;
	}

	public Law(String id, Industry industry, String title, Date publishTime, String content, String type,
			Integer readCount, String projectStage, Set lawLabels) {
		this.id = id;
		this.industry = industry;
		this.title = title;
		this.publishTime = publishTime;
		this.content = content;
		this.type = type;
		this.readCount = readCount;
		this.projectStage = projectStage;
		this.lawLabels = lawLabels;
	}

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public Industry getIndustry() {
		return this.industry;
	}

	public void setIndustry(Industry industry) {
		this.industry = industry;
	}

	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public Date getPublishTime() {
		return this.publishTime;
	}

	public void setPublishTime(Date publishTime) {
		this.publishTime = publishTime;
	}

	public String getContent() {
		return this.content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	public Integer getReadCount() {
		return this.readCount;
	}

	public void setReadCount(Integer readCount) {
		this.readCount = readCount;
	}

	public String getProjectStage() {
		return this.projectStage;
	}

	public void setProjectStage(String projectStage) {
		this.projectStage = projectStage;
	}

	public Set getLawLabels() {
		return this.lawLabels;
	}

	public void setLawLabels(Set lawLabels) {
		this.lawLabels = lawLabels;
	}

}
