package org.sicdlab.entrepreneur.beans;
// Generated 2015-7-27 16:33:46 by Hibernate Tools 4.3.1

/**
 * LawLabel generated by hbm2java
 */
public class LawLabel implements java.io.Serializable {

	private String id;
	private Label label;
	private Law law;

	public LawLabel() {
	}

	public LawLabel(String id, Label label, Law law) {
		this.id = id;
		this.label = label;
		this.law = law;
	}

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public Label getLabel() {
		return this.label;
	}

	public void setLabel(Label label) {
		this.label = label;
	}

	public Law getLaw() {
		return this.law;
	}

	public void setLaw(Law law) {
		this.law = law;
	}

}
