package org.sicdlab.entrepreneur.beans;
// Generated 2015-7-27 16:33:46 by Hibernate Tools 4.3.1

import java.util.Date;

/**
 * Mail generated by hbm2java
 */
public class Mail implements java.io.Serializable {

	private String id;
	private User userBySenderId;
	private User userByReceiverId;
	private String title;
	private String content;
	private Date sendTime;
	private String status;

	public Mail() {
	}

	public Mail(String id, User userBySenderId, User userByReceiverId, Date sendTime, String status) {
		this.id = id;
		this.userBySenderId = userBySenderId;
		this.userByReceiverId = userByReceiverId;
		this.sendTime = sendTime;
		this.status = status;
	}

	public Mail(String id, User userBySenderId, User userByReceiverId, String title, String content, Date sendTime,
			String status) {
		this.id = id;
		this.userBySenderId = userBySenderId;
		this.userByReceiverId = userByReceiverId;
		this.title = title;
		this.content = content;
		this.sendTime = sendTime;
		this.status = status;
	}

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public User getUserBySenderId() {
		return this.userBySenderId;
	}

	public void setUserBySenderId(User userBySenderId) {
		this.userBySenderId = userBySenderId;
	}

	public User getUserByReceiverId() {
		return this.userByReceiverId;
	}

	public void setUserByReceiverId(User userByReceiverId) {
		this.userByReceiverId = userByReceiverId;
	}

	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public String getContent() {
		return this.content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	public Date getSendTime() {
		return this.sendTime;
	}

	public void setSendTime(Date sendTime) {
		this.sendTime = sendTime;
	}

	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

}
