package org.sicdlab.entrepreneur.beans;
// Generated 2015-8-5 16:28:47 by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Mail generated by hbm2java
 */
@Entity
@Table(name = "mail", catalog = "entrepreneur_2015")
public class Mail implements java.io.Serializable {

	private String id;
	private User userBySenderId;
	private User userByReceiverId;
	private String title;
	private String content;
	private Date sendTime;
	private String status;

	public Mail() {
	}

	public Mail(String id, User userBySenderId, User userByReceiverId, Date sendTime, String status) {
		this.id = id;
		this.userBySenderId = userBySenderId;
		this.userByReceiverId = userByReceiverId;
		this.sendTime = sendTime;
		this.status = status;
	}

	public Mail(String id, User userBySenderId, User userByReceiverId, String title, String content, Date sendTime, String status) {
		this.id = id;
		this.userBySenderId = userBySenderId;
		this.userByReceiverId = userByReceiverId;
		this.title = title;
		this.content = content;
		this.sendTime = sendTime;
		this.status = status;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false, length = 32)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "sender_id", nullable = false)
	public User getUserBySenderId() {
		return this.userBySenderId;
	}

	public void setUserBySenderId(User userBySenderId) {
		this.userBySenderId = userBySenderId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "receiver_id", nullable = false)
	public User getUserByReceiverId() {
		return this.userByReceiverId;
	}

	public void setUserByReceiverId(User userByReceiverId) {
		this.userByReceiverId = userByReceiverId;
	}

	@Column(name = "title", length = 45)
	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	@Column(name = "content", length = 65535)
	public String getContent() {
		return this.content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "send_time", nullable = false, length = 19)
	public Date getSendTime() {
		return this.sendTime;
	}

	public void setSendTime(Date sendTime) {
		this.sendTime = sendTime;
	}

	@Column(name = "status", nullable = false, length = 50)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

}
