package org.sicdlab.entrepreneur.beans;
// Generated 2015-8-5 16:28:47 by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * ManagementRisk generated by hbm2java
 */
@Entity
@Table(name = "management_risk", catalog = "entrepreneur_2015")
public class ManagementRisk implements java.io.Serializable {

	private String managementRiskId;
	private float safetyControlDegree;
	private float taxPlanning;
	private float organizationPromiseDegree;
	private float totalScore;
	private String comment;
	private Set managementTeams = new HashSet(0);

	public ManagementRisk() {
	}

	public ManagementRisk(String managementRiskId, float safetyControlDegree, float taxPlanning, float organizationPromiseDegree, float totalScore) {
		this.managementRiskId = managementRiskId;
		this.safetyControlDegree = safetyControlDegree;
		this.taxPlanning = taxPlanning;
		this.organizationPromiseDegree = organizationPromiseDegree;
		this.totalScore = totalScore;
	}

	public ManagementRisk(String managementRiskId, float safetyControlDegree, float taxPlanning, float organizationPromiseDegree, float totalScore, String comment,
			Set managementTeams) {
		this.managementRiskId = managementRiskId;
		this.safetyControlDegree = safetyControlDegree;
		this.taxPlanning = taxPlanning;
		this.organizationPromiseDegree = organizationPromiseDegree;
		this.totalScore = totalScore;
		this.comment = comment;
		this.managementTeams = managementTeams;
	}

	@Id

	@Column(name = "MANAGEMENT_RISK_ID", unique = true, nullable = false, length = 32)
	public String getManagementRiskId() {
		return this.managementRiskId;
	}

	public void setManagementRiskId(String managementRiskId) {
		this.managementRiskId = managementRiskId;
	}

	@Column(name = "SAFETY_CONTROL_DEGREE", nullable = false, precision = 10)
	public float getSafetyControlDegree() {
		return this.safetyControlDegree;
	}

	public void setSafetyControlDegree(float safetyControlDegree) {
		this.safetyControlDegree = safetyControlDegree;
	}

	@Column(name = "TAX_PLANNING", nullable = false, precision = 10)
	public float getTaxPlanning() {
		return this.taxPlanning;
	}

	public void setTaxPlanning(float taxPlanning) {
		this.taxPlanning = taxPlanning;
	}

	@Column(name = "ORGANIZATION_PROMISE_DEGREE", nullable = false, precision = 10)
	public float getOrganizationPromiseDegree() {
		return this.organizationPromiseDegree;
	}

	public void setOrganizationPromiseDegree(float organizationPromiseDegree) {
		this.organizationPromiseDegree = organizationPromiseDegree;
	}

	@Column(name = "TOTAL_SCORE", nullable = false, precision = 10)
	public float getTotalScore() {
		return this.totalScore;
	}

	public void setTotalScore(float totalScore) {
		this.totalScore = totalScore;
	}

	@Column(name = "COMMENT", length = 65535)
	public String getComment() {
		return this.comment;
	}

	public void setComment(String comment) {
		this.comment = comment;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "managementRisk")
	public Set getManagementTeams() {
		return this.managementTeams;
	}

	public void setManagementTeams(Set managementTeams) {
		this.managementTeams = managementTeams;
	}

}
