package org.sicdlab.entrepreneur.beans;
// Generated 2015-7-27 16:33:46 by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

/**
 * ManagementTeam generated by hbm2java
 */
public class ManagementTeam implements java.io.Serializable {

	private String managementTeamId;
	private ManagementRisk managementRisk;
	private TeamCoreCompetence teamCoreCompetence;
	private String comment;
	private float leaderQualityScore;
	private float totalScore;
	private Set projectIndexes = new HashSet(0);

	public ManagementTeam() {
	}

	public ManagementTeam(String managementTeamId, ManagementRisk managementRisk, TeamCoreCompetence teamCoreCompetence,
			float leaderQualityScore, float totalScore) {
		this.managementTeamId = managementTeamId;
		this.managementRisk = managementRisk;
		this.teamCoreCompetence = teamCoreCompetence;
		this.leaderQualityScore = leaderQualityScore;
		this.totalScore = totalScore;
	}

	public ManagementTeam(String managementTeamId, ManagementRisk managementRisk, TeamCoreCompetence teamCoreCompetence,
			String comment, float leaderQualityScore, float totalScore, Set projectIndexes) {
		this.managementTeamId = managementTeamId;
		this.managementRisk = managementRisk;
		this.teamCoreCompetence = teamCoreCompetence;
		this.comment = comment;
		this.leaderQualityScore = leaderQualityScore;
		this.totalScore = totalScore;
		this.projectIndexes = projectIndexes;
	}

	public String getManagementTeamId() {
		return this.managementTeamId;
	}

	public void setManagementTeamId(String managementTeamId) {
		this.managementTeamId = managementTeamId;
	}

	public ManagementRisk getManagementRisk() {
		return this.managementRisk;
	}

	public void setManagementRisk(ManagementRisk managementRisk) {
		this.managementRisk = managementRisk;
	}

	public TeamCoreCompetence getTeamCoreCompetence() {
		return this.teamCoreCompetence;
	}

	public void setTeamCoreCompetence(TeamCoreCompetence teamCoreCompetence) {
		this.teamCoreCompetence = teamCoreCompetence;
	}

	public String getComment() {
		return this.comment;
	}

	public void setComment(String comment) {
		this.comment = comment;
	}

	public float getLeaderQualityScore() {
		return this.leaderQualityScore;
	}

	public void setLeaderQualityScore(float leaderQualityScore) {
		this.leaderQualityScore = leaderQualityScore;
	}

	public float getTotalScore() {
		return this.totalScore;
	}

	public void setTotalScore(float totalScore) {
		this.totalScore = totalScore;
	}

	public Set getProjectIndexes() {
		return this.projectIndexes;
	}

	public void setProjectIndexes(Set projectIndexes) {
		this.projectIndexes = projectIndexes;
	}

}
