package org.sicdlab.entrepreneur.beans;
// Generated 2015-7-27 16:33:46 by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

/**
 * ManagementRisk generated by hbm2java
 */
public class ManagementRisk implements java.io.Serializable {

	private String managementRiskId;
	private float safetyControlDegree;
	private float taxPlanning;
	private float organizationPromiseDegree;
	private float totalScore;
	private String comment;
	private Set managementTeams = new HashSet(0);

	public ManagementRisk() {
	}

	public ManagementRisk(String managementRiskId, float safetyControlDegree, float taxPlanning,
			float organizationPromiseDegree, float totalScore) {
		this.managementRiskId = managementRiskId;
		this.safetyControlDegree = safetyControlDegree;
		this.taxPlanning = taxPlanning;
		this.organizationPromiseDegree = organizationPromiseDegree;
		this.totalScore = totalScore;
	}

	public ManagementRisk(String managementRiskId, float safetyControlDegree, float taxPlanning,
			float organizationPromiseDegree, float totalScore, String comment, Set managementTeams) {
		this.managementRiskId = managementRiskId;
		this.safetyControlDegree = safetyControlDegree;
		this.taxPlanning = taxPlanning;
		this.organizationPromiseDegree = organizationPromiseDegree;
		this.totalScore = totalScore;
		this.comment = comment;
		this.managementTeams = managementTeams;
	}

	public String getManagementRiskId() {
		return this.managementRiskId;
	}

	public void setManagementRiskId(String managementRiskId) {
		this.managementRiskId = managementRiskId;
	}

	public float getSafetyControlDegree() {
		return this.safetyControlDegree;
	}

	public void setSafetyControlDegree(float safetyControlDegree) {
		this.safetyControlDegree = safetyControlDegree;
	}

	public float getTaxPlanning() {
		return this.taxPlanning;
	}

	public void setTaxPlanning(float taxPlanning) {
		this.taxPlanning = taxPlanning;
	}

	public float getOrganizationPromiseDegree() {
		return this.organizationPromiseDegree;
	}

	public void setOrganizationPromiseDegree(float organizationPromiseDegree) {
		this.organizationPromiseDegree = organizationPromiseDegree;
	}

	public float getTotalScore() {
		return this.totalScore;
	}

	public void setTotalScore(float totalScore) {
		this.totalScore = totalScore;
	}

	public String getComment() {
		return this.comment;
	}

	public void setComment(String comment) {
		this.comment = comment;
	}

	public Set getManagementTeams() {
		return this.managementTeams;
	}

	public void setManagementTeams(Set managementTeams) {
		this.managementTeams = managementTeams;
	}

}
