package org.sicdlab.entrepreneur.beans;
// Generated 2015-8-5 16:28:47 by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * MarketAssessFactor generated by hbm2java
 */
@Entity
@Table(name = "market_assess_factor", catalog = "entrepreneur_2015")
public class MarketAssessFactor implements java.io.Serializable {

	private String marketAssessFactorId;
	private float marketScale;
	private float valueChainTransferEfficiency;
	private float riseContinuity;
	private float entryBarrier;
	private float clientValue;
	private float totalScore;
	private String comment;
	private Set projectIndexes = new HashSet(0);

	public MarketAssessFactor() {
	}

	public MarketAssessFactor(String marketAssessFactorId, float marketScale, float valueChainTransferEfficiency, float riseContinuity, float entryBarrier, float clientValue,
			float totalScore) {
		this.marketAssessFactorId = marketAssessFactorId;
		this.marketScale = marketScale;
		this.valueChainTransferEfficiency = valueChainTransferEfficiency;
		this.riseContinuity = riseContinuity;
		this.entryBarrier = entryBarrier;
		this.clientValue = clientValue;
		this.totalScore = totalScore;
	}

	public MarketAssessFactor(String marketAssessFactorId, float marketScale, float valueChainTransferEfficiency, float riseContinuity, float entryBarrier, float clientValue,
			float totalScore, String comment, Set projectIndexes) {
		this.marketAssessFactorId = marketAssessFactorId;
		this.marketScale = marketScale;
		this.valueChainTransferEfficiency = valueChainTransferEfficiency;
		this.riseContinuity = riseContinuity;
		this.entryBarrier = entryBarrier;
		this.clientValue = clientValue;
		this.totalScore = totalScore;
		this.comment = comment;
		this.projectIndexes = projectIndexes;
	}

	@Id

	@Column(name = "MARKET_ASSESS_FACTOR_ID", unique = true, nullable = false, length = 32)
	public String getMarketAssessFactorId() {
		return this.marketAssessFactorId;
	}

	public void setMarketAssessFactorId(String marketAssessFactorId) {
		this.marketAssessFactorId = marketAssessFactorId;
	}

	@Column(name = "MARKET_SCALE", nullable = false, precision = 10)
	public float getMarketScale() {
		return this.marketScale;
	}

	public void setMarketScale(float marketScale) {
		this.marketScale = marketScale;
	}

	@Column(name = "VALUE_CHAIN_TRANSFER_EFFICIENCY", nullable = false, precision = 10)
	public float getValueChainTransferEfficiency() {
		return this.valueChainTransferEfficiency;
	}

	public void setValueChainTransferEfficiency(float valueChainTransferEfficiency) {
		this.valueChainTransferEfficiency = valueChainTransferEfficiency;
	}

	@Column(name = "RISE_CONTINUITY", nullable = false, precision = 10)
	public float getRiseContinuity() {
		return this.riseContinuity;
	}

	public void setRiseContinuity(float riseContinuity) {
		this.riseContinuity = riseContinuity;
	}

	@Column(name = "ENTRY_BARRIER", nullable = false, precision = 10)
	public float getEntryBarrier() {
		return this.entryBarrier;
	}

	public void setEntryBarrier(float entryBarrier) {
		this.entryBarrier = entryBarrier;
	}

	@Column(name = "CLIENT_VALUE", nullable = false, precision = 10)
	public float getClientValue() {
		return this.clientValue;
	}

	public void setClientValue(float clientValue) {
		this.clientValue = clientValue;
	}

	@Column(name = "TOTAL_SCORE", nullable = false, precision = 10)
	public float getTotalScore() {
		return this.totalScore;
	}

	public void setTotalScore(float totalScore) {
		this.totalScore = totalScore;
	}

	@Column(name = "COMMENT", length = 65535)
	public String getComment() {
		return this.comment;
	}

	public void setComment(String comment) {
		this.comment = comment;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "marketAssessFactor")
	public Set getProjectIndexes() {
		return this.projectIndexes;
	}

	public void setProjectIndexes(Set projectIndexes) {
		this.projectIndexes = projectIndexes;
	}

}
