package org.sicdlab.entrepreneur.beans;
// Generated 2015-7-27 16:33:46 by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

/**
 * MarketAssessFactor generated by hbm2java
 */
public class MarketAssessFactor implements java.io.Serializable {

	private String marketAssessFactorId;
	private float marketScale;
	private float valueChainTransferEfficiency;
	private float riseContinuity;
	private float entryBarrier;
	private float clientValue;
	private float totalScore;
	private String comment;
	private Set projectIndexes = new HashSet(0);

	public MarketAssessFactor() {
	}

	public MarketAssessFactor(String marketAssessFactorId, float marketScale, float valueChainTransferEfficiency,
			float riseContinuity, float entryBarrier, float clientValue, float totalScore) {
		this.marketAssessFactorId = marketAssessFactorId;
		this.marketScale = marketScale;
		this.valueChainTransferEfficiency = valueChainTransferEfficiency;
		this.riseContinuity = riseContinuity;
		this.entryBarrier = entryBarrier;
		this.clientValue = clientValue;
		this.totalScore = totalScore;
	}

	public MarketAssessFactor(String marketAssessFactorId, float marketScale, float valueChainTransferEfficiency,
			float riseContinuity, float entryBarrier, float clientValue, float totalScore, String comment,
			Set projectIndexes) {
		this.marketAssessFactorId = marketAssessFactorId;
		this.marketScale = marketScale;
		this.valueChainTransferEfficiency = valueChainTransferEfficiency;
		this.riseContinuity = riseContinuity;
		this.entryBarrier = entryBarrier;
		this.clientValue = clientValue;
		this.totalScore = totalScore;
		this.comment = comment;
		this.projectIndexes = projectIndexes;
	}

	public String getMarketAssessFactorId() {
		return this.marketAssessFactorId;
	}

	public void setMarketAssessFactorId(String marketAssessFactorId) {
		this.marketAssessFactorId = marketAssessFactorId;
	}

	public float getMarketScale() {
		return this.marketScale;
	}

	public void setMarketScale(float marketScale) {
		this.marketScale = marketScale;
	}

	public float getValueChainTransferEfficiency() {
		return this.valueChainTransferEfficiency;
	}

	public void setValueChainTransferEfficiency(float valueChainTransferEfficiency) {
		this.valueChainTransferEfficiency = valueChainTransferEfficiency;
	}

	public float getRiseContinuity() {
		return this.riseContinuity;
	}

	public void setRiseContinuity(float riseContinuity) {
		this.riseContinuity = riseContinuity;
	}

	public float getEntryBarrier() {
		return this.entryBarrier;
	}

	public void setEntryBarrier(float entryBarrier) {
		this.entryBarrier = entryBarrier;
	}

	public float getClientValue() {
		return this.clientValue;
	}

	public void setClientValue(float clientValue) {
		this.clientValue = clientValue;
	}

	public float getTotalScore() {
		return this.totalScore;
	}

	public void setTotalScore(float totalScore) {
		this.totalScore = totalScore;
	}

	public String getComment() {
		return this.comment;
	}

	public void setComment(String comment) {
		this.comment = comment;
	}

	public Set getProjectIndexes() {
		return this.projectIndexes;
	}

	public void setProjectIndexes(Set projectIndexes) {
		this.projectIndexes = projectIndexes;
	}

}
