package org.sicdlab.entrepreneur.beans;
// Generated 2015-7-27 16:33:46 by Hibernate Tools 4.3.1

/**
 * NeedLabel generated by hbm2java
 */
public class NeedLabel implements java.io.Serializable {

	private String id;
	private Label label;
	private Need need;

	public NeedLabel() {
	}

	public NeedLabel(String id, Label label, Need need) {
		this.id = id;
		this.label = label;
		this.need = need;
	}

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public Label getLabel() {
		return this.label;
	}

	public void setLabel(Label label) {
		this.label = label;
	}

	public Need getNeed() {
		return this.need;
	}

	public void setNeed(Need need) {
		this.need = need;
	}

}
