package org.sicdlab.entrepreneur.beans;
// Generated 2015-7-27 16:33:46 by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Need generated by hbm2java
 */
public class Need implements java.io.Serializable {

	private String id;
	private Industry industry;
	private User user;
	private String title;
	private String type;
	private String content;
	private Date publishTime;
	private String contact;
	private String fundAmount;
	private String lackFund;
	private String fundType;
	private String projectName;
	private String email;
	private String area;
	private Set needLabels = new HashSet(0);

	public Need() {
	}

	public Need(String id, User user, String title, String type, Date publishTime, String projectName) {
		this.id = id;
		this.user = user;
		this.title = title;
		this.type = type;
		this.publishTime = publishTime;
		this.projectName = projectName;
	}

	public Need(String id, Industry industry, User user, String title, String type, String content, Date publishTime,
			String contact, String fundAmount, String lackFund, String fundType, String projectName, String email,
			String area, Set needLabels) {
		this.id = id;
		this.industry = industry;
		this.user = user;
		this.title = title;
		this.type = type;
		this.content = content;
		this.publishTime = publishTime;
		this.contact = contact;
		this.fundAmount = fundAmount;
		this.lackFund = lackFund;
		this.fundType = fundType;
		this.projectName = projectName;
		this.email = email;
		this.area = area;
		this.needLabels = needLabels;
	}

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public Industry getIndustry() {
		return this.industry;
	}

	public void setIndustry(Industry industry) {
		this.industry = industry;
	}

	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	public String getContent() {
		return this.content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	public Date getPublishTime() {
		return this.publishTime;
	}

	public void setPublishTime(Date publishTime) {
		this.publishTime = publishTime;
	}

	public String getContact() {
		return this.contact;
	}

	public void setContact(String contact) {
		this.contact = contact;
	}

	public String getFundAmount() {
		return this.fundAmount;
	}

	public void setFundAmount(String fundAmount) {
		this.fundAmount = fundAmount;
	}

	public String getLackFund() {
		return this.lackFund;
	}

	public void setLackFund(String lackFund) {
		this.lackFund = lackFund;
	}

	public String getFundType() {
		return this.fundType;
	}

	public void setFundType(String fundType) {
		this.fundType = fundType;
	}

	public String getProjectName() {
		return this.projectName;
	}

	public void setProjectName(String projectName) {
		this.projectName = projectName;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getArea() {
		return this.area;
	}

	public void setArea(String area) {
		this.area = area;
	}

	public Set getNeedLabels() {
		return this.needLabels;
	}

	public void setNeedLabels(Set needLabels) {
		this.needLabels = needLabels;
	}

}
