package org.sicdlab.entrepreneur.beans;
// Generated 2015-8-5 16:28:47 by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * NewsInfo generated by hbm2java
 */
@Entity
@Table(name = "news_info", catalog = "entrepreneur_2015")
public class NewsInfo implements java.io.Serializable {

	private String id;
	private String newsInfoType;
	private String title;
	private String content;
	private Date publishTime;
	private Integer readTimes;

	public NewsInfo() {
	}

	public NewsInfo(String id) {
		this.id = id;
	}

	public NewsInfo(String id, String newsInfoType, String title, String content, Date publishTime, Integer readTimes) {
		this.id = id;
		this.newsInfoType = newsInfoType;
		this.title = title;
		this.content = content;
		this.publishTime = publishTime;
		this.readTimes = readTimes;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false, length = 32)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@Column(name = "news_info_type", length = 50)
	public String getNewsInfoType() {
		return this.newsInfoType;
	}

	public void setNewsInfoType(String newsInfoType) {
		this.newsInfoType = newsInfoType;
	}

	@Column(name = "title", length = 200)
	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	@Column(name = "content", length = 65535)
	public String getContent() {
		return this.content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "publish_time", length = 19)
	public Date getPublishTime() {
		return this.publishTime;
	}

	public void setPublishTime(Date publishTime) {
		this.publishTime = publishTime;
	}

	@Column(name = "read_times")
	public Integer getReadTimes() {
		return this.readTimes;
	}

	public void setReadTimes(Integer readTimes) {
		this.readTimes = readTimes;
	}

}
