package org.sicdlab.entrepreneur.beans;
// Generated 2015-7-27 16:33:46 by Hibernate Tools 4.3.1

import java.util.Date;

/**
 * NewsInfo generated by hbm2java
 */
public class NewsInfo implements java.io.Serializable {

	private String id;
	private String newsInfoType;
	private String title;
	private String content;
	private Date publishTime;
	private Integer readTimes;

	public NewsInfo() {
	}

	public NewsInfo(String id) {
		this.id = id;
	}

	public NewsInfo(String id, String newsInfoType, String title, String content, Date publishTime, Integer readTimes) {
		this.id = id;
		this.newsInfoType = newsInfoType;
		this.title = title;
		this.content = content;
		this.publishTime = publishTime;
		this.readTimes = readTimes;
	}

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getNewsInfoType() {
		return this.newsInfoType;
	}

	public void setNewsInfoType(String newsInfoType) {
		this.newsInfoType = newsInfoType;
	}

	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public String getContent() {
		return this.content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	public Date getPublishTime() {
		return this.publishTime;
	}

	public void setPublishTime(Date publishTime) {
		this.publishTime = publishTime;
	}

	public Integer getReadTimes() {
		return this.readTimes;
	}

	public void setReadTimes(Integer readTimes) {
		this.readTimes = readTimes;
	}

}
