package org.sicdlab.entrepreneur.beans;
// Generated 2015-7-27 16:33:46 by Hibernate Tools 4.3.1

import java.util.Date;

/**
 * Notice generated by hbm2java
 */
public class Notice implements java.io.Serializable {

	private String id;
	private User user;
	private String title;
	private String content;
	private Date sendTime;
	private String status;

	public Notice() {
	}

	public Notice(String id, User user) {
		this.id = id;
		this.user = user;
	}

	public Notice(String id, User user, String title, String content, Date sendTime, String status) {
		this.id = id;
		this.user = user;
		this.title = title;
		this.content = content;
		this.sendTime = sendTime;
		this.status = status;
	}

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public String getContent() {
		return this.content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	public Date getSendTime() {
		return this.sendTime;
	}

	public void setSendTime(Date sendTime) {
		this.sendTime = sendTime;
	}

	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

}
