package org.sicdlab.entrepreneur.beans;
// Generated 2015-7-27 16:33:46 by Hibernate Tools 4.3.1

import java.util.Date;

/**
 * NoticeTemplate generated by hbm2java
 */
public class NoticeTemplate implements java.io.Serializable {

	private String id;
	private String title;
	private String content;
	private Date sendTime;
	private String noticeType;

	public NoticeTemplate() {
	}

	public NoticeTemplate(String id) {
		this.id = id;
	}

	public NoticeTemplate(String id, String title, String content, Date sendTime, String noticeType) {
		this.id = id;
		this.title = title;
		this.content = content;
		this.sendTime = sendTime;
		this.noticeType = noticeType;
	}

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public String getContent() {
		return this.content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	public Date getSendTime() {
		return this.sendTime;
	}

	public void setSendTime(Date sendTime) {
		this.sendTime = sendTime;
	}

	public String getNoticeType() {
		return this.noticeType;
	}

	public void setNoticeType(String noticeType) {
		this.noticeType = noticeType;
	}

}
