package org.sicdlab.entrepreneur.beans;
// Generated 2015-7-27 16:33:46 by Hibernate Tools 4.3.1

import java.util.Date;

/**
 * OperationLog generated by hbm2java
 */
public class OperationLog implements java.io.Serializable {

	private String id;
	private User user;
	private String ip;
	private String browser;
	private String operation;
	private Date time;

	public OperationLog() {
	}

	public OperationLog(String id, User user) {
		this.id = id;
		this.user = user;
	}

	public OperationLog(String id, User user, String ip, String browser, String operation, Date time) {
		this.id = id;
		this.user = user;
		this.ip = ip;
		this.browser = browser;
		this.operation = operation;
		this.time = time;
	}

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	public String getIp() {
		return this.ip;
	}

	public void setIp(String ip) {
		this.ip = ip;
	}

	public String getBrowser() {
		return this.browser;
	}

	public void setBrowser(String browser) {
		this.browser = browser;
	}

	public String getOperation() {
		return this.operation;
	}

	public void setOperation(String operation) {
		this.operation = operation;
	}

	public Date getTime() {
		return this.time;
	}

	public void setTime(Date time) {
		this.time = time;
	}

}
