package org.sicdlab.entrepreneur.beans;
// Generated 2015-7-27 16:33:46 by Hibernate Tools 4.3.1

/**
 * PolicyLabel generated by hbm2java
 */
public class PolicyLabel implements java.io.Serializable {

	private String id;
	private Label label;
	private Policy policy;

	public PolicyLabel() {
	}

	public PolicyLabel(String id, Label label, Policy policy) {
		this.id = id;
		this.label = label;
		this.policy = policy;
	}

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public Label getLabel() {
		return this.label;
	}

	public void setLabel(Label label) {
		this.label = label;
	}

	public Policy getPolicy() {
		return this.policy;
	}

	public void setPolicy(Policy policy) {
		this.policy = policy;
	}

}
