package org.sicdlab.entrepreneur.beans;
// Generated 2015-7-27 16:33:46 by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Policy generated by hbm2java
 */
public class Policy implements java.io.Serializable {

	private String id;
	private Industry industry;
	private String title;
	private Date publishTime;
	private String content;
	private String type;
	private String area;
	private int readCount;
	private String projectStage;
	private Set policyLabels = new HashSet(0);

	public Policy() {
	}

	public Policy(String id, String title, Date publishTime, String content, String type, int readCount,
			String projectStage) {
		this.id = id;
		this.title = title;
		this.publishTime = publishTime;
		this.content = content;
		this.type = type;
		this.readCount = readCount;
		this.projectStage = projectStage;
	}

	public Policy(String id, Industry industry, String title, Date publishTime, String content, String type,
			String area, int readCount, String projectStage, Set policyLabels) {
		this.id = id;
		this.industry = industry;
		this.title = title;
		this.publishTime = publishTime;
		this.content = content;
		this.type = type;
		this.area = area;
		this.readCount = readCount;
		this.projectStage = projectStage;
		this.policyLabels = policyLabels;
	}

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public Industry getIndustry() {
		return this.industry;
	}

	public void setIndustry(Industry industry) {
		this.industry = industry;
	}

	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public Date getPublishTime() {
		return this.publishTime;
	}

	public void setPublishTime(Date publishTime) {
		this.publishTime = publishTime;
	}

	public String getContent() {
		return this.content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	public String getArea() {
		return this.area;
	}

	public void setArea(String area) {
		this.area = area;
	}

	public int getReadCount() {
		return this.readCount;
	}

	public void setReadCount(int readCount) {
		this.readCount = readCount;
	}

	public String getProjectStage() {
		return this.projectStage;
	}

	public void setProjectStage(String projectStage) {
		this.projectStage = projectStage;
	}

	public Set getPolicyLabels() {
		return this.policyLabels;
	}

	public void setPolicyLabels(Set policyLabels) {
		this.policyLabels = policyLabels;
	}

}
