package org.sicdlab.entrepreneur.beans;
// Generated 2015-7-27 16:33:46 by Hibernate Tools 4.3.1

import java.util.Date;

/**
 * ProjectTutor generated by hbm2java
 */
public class ProjectTutor implements java.io.Serializable {

	private String id;
	private Project project;
	private ProjectIndex projectIndex;
	private Tutor tutor;
	private String accessStatus;
	private String comment;
	private Float score;
	private Date sendTime;
	private Date finishedTime;
	private Date commentTime;
	private String gradeStatus;

	public ProjectTutor() {
	}

	public ProjectTutor(String id, Project project, Tutor tutor) {
		this.id = id;
		this.project = project;
		this.tutor = tutor;
	}

	public ProjectTutor(String id, Project project, ProjectIndex projectIndex, Tutor tutor, String accessStatus,
			String comment, Float score, Date sendTime, Date finishedTime, Date commentTime, String gradeStatus) {
		this.id = id;
		this.project = project;
		this.projectIndex = projectIndex;
		this.tutor = tutor;
		this.accessStatus = accessStatus;
		this.comment = comment;
		this.score = score;
		this.sendTime = sendTime;
		this.finishedTime = finishedTime;
		this.commentTime = commentTime;
		this.gradeStatus = gradeStatus;
	}

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public Project getProject() {
		return this.project;
	}

	public void setProject(Project project) {
		this.project = project;
	}

	public ProjectIndex getProjectIndex() {
		return this.projectIndex;
	}

	public void setProjectIndex(ProjectIndex projectIndex) {
		this.projectIndex = projectIndex;
	}

	public Tutor getTutor() {
		return this.tutor;
	}

	public void setTutor(Tutor tutor) {
		this.tutor = tutor;
	}

	public String getAccessStatus() {
		return this.accessStatus;
	}

	public void setAccessStatus(String accessStatus) {
		this.accessStatus = accessStatus;
	}

	public String getComment() {
		return this.comment;
	}

	public void setComment(String comment) {
		this.comment = comment;
	}

	public Float getScore() {
		return this.score;
	}

	public void setScore(Float score) {
		this.score = score;
	}

	public Date getSendTime() {
		return this.sendTime;
	}

	public void setSendTime(Date sendTime) {
		this.sendTime = sendTime;
	}

	public Date getFinishedTime() {
		return this.finishedTime;
	}

	public void setFinishedTime(Date finishedTime) {
		this.finishedTime = finishedTime;
	}

	public Date getCommentTime() {
		return this.commentTime;
	}

	public void setCommentTime(Date commentTime) {
		this.commentTime = commentTime;
	}

	public String getGradeStatus() {
		return this.gradeStatus;
	}

	public void setGradeStatus(String gradeStatus) {
		this.gradeStatus = gradeStatus;
	}

}
