package org.sicdlab.entrepreneur.beans;
// Generated 2015-8-5 16:28:47 by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ProjectTutor generated by hbm2java
 */
@Entity
@Table(name = "project_tutor", catalog = "entrepreneur_2015")
public class ProjectTutor implements java.io.Serializable {

	private String id;
	private Project project;
	private ProjectIndex projectIndex;
	private Tutor tutor;
	private String accessStatus;
	private String comment;
	private Float score;
	private Date sendTime;
	private Date finishedTime;
	private Date commentTime;
	private String gradeStatus;

	public ProjectTutor() {
	}

	public ProjectTutor(String id, Project project, Tutor tutor) {
		this.id = id;
		this.project = project;
		this.tutor = tutor;
	}

	public ProjectTutor(String id, Project project, ProjectIndex projectIndex, Tutor tutor, String accessStatus, String comment, Float score, Date sendTime, Date finishedTime,
			Date commentTime, String gradeStatus) {
		this.id = id;
		this.project = project;
		this.projectIndex = projectIndex;
		this.tutor = tutor;
		this.accessStatus = accessStatus;
		this.comment = comment;
		this.score = score;
		this.sendTime = sendTime;
		this.finishedTime = finishedTime;
		this.commentTime = commentTime;
		this.gradeStatus = gradeStatus;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false, length = 32)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "project_id", nullable = false)
	public Project getProject() {
		return this.project;
	}

	public void setProject(Project project) {
		this.project = project;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "project_index_id")
	public ProjectIndex getProjectIndex() {
		return this.projectIndex;
	}

	public void setProjectIndex(ProjectIndex projectIndex) {
		this.projectIndex = projectIndex;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "tutor_id", nullable = false)
	public Tutor getTutor() {
		return this.tutor;
	}

	public void setTutor(Tutor tutor) {
		this.tutor = tutor;
	}

	@Column(name = "access_status", length = 50)
	public String getAccessStatus() {
		return this.accessStatus;
	}

	public void setAccessStatus(String accessStatus) {
		this.accessStatus = accessStatus;
	}

	@Column(name = "comment", length = 500)
	public String getComment() {
		return this.comment;
	}

	public void setComment(String comment) {
		this.comment = comment;
	}

	@Column(name = "score", precision = 10)
	public Float getScore() {
		return this.score;
	}

	public void setScore(Float score) {
		this.score = score;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "send_time", length = 19)
	public Date getSendTime() {
		return this.sendTime;
	}

	public void setSendTime(Date sendTime) {
		this.sendTime = sendTime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "finished_time", length = 19)
	public Date getFinishedTime() {
		return this.finishedTime;
	}

	public void setFinishedTime(Date finishedTime) {
		this.finishedTime = finishedTime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "comment_time", length = 19)
	public Date getCommentTime() {
		return this.commentTime;
	}

	public void setCommentTime(Date commentTime) {
		this.commentTime = commentTime;
	}

	@Column(name = "grade_status", length = 50)
	public String getGradeStatus() {
		return this.gradeStatus;
	}

	public void setGradeStatus(String gradeStatus) {
		this.gradeStatus = gradeStatus;
	}

}
