package org.sicdlab.entrepreneur.beans;
// Generated 2015-8-5 16:28:47 by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * ProjectInstitution generated by hbm2java
 */
@Entity
@Table(name = "project_institution", catalog = "entrepreneur_2015", uniqueConstraints = @UniqueConstraint(columnNames = "project_id") )
public class ProjectInstitution implements java.io.Serializable {

	private String id;
	private Institution institution;
	private Project project;
	private String content;
	private String applyType;
	private String title;
	private Date sendTime;
	private String applyStatus;
	private Date agreeTime;

	public ProjectInstitution() {
	}

	public ProjectInstitution(String id, Institution institution, Project project) {
		this.id = id;
		this.institution = institution;
		this.project = project;
	}

	public ProjectInstitution(String id, Institution institution, Project project, String content, String applyType, String title, Date sendTime, String applyStatus,
			Date agreeTime) {
		this.id = id;
		this.institution = institution;
		this.project = project;
		this.content = content;
		this.applyType = applyType;
		this.title = title;
		this.sendTime = sendTime;
		this.applyStatus = applyStatus;
		this.agreeTime = agreeTime;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false, length = 32)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "institution_id", nullable = false)
	public Institution getInstitution() {
		return this.institution;
	}

	public void setInstitution(Institution institution) {
		this.institution = institution;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "project_id", unique = true, nullable = false)
	public Project getProject() {
		return this.project;
	}

	public void setProject(Project project) {
		this.project = project;
	}

	@Column(name = "content", length = 200)
	public String getContent() {
		return this.content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	@Column(name = "apply_type", length = 32)
	public String getApplyType() {
		return this.applyType;
	}

	public void setApplyType(String applyType) {
		this.applyType = applyType;
	}

	@Column(name = "title", length = 32)
	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "send_time", length = 19)
	public Date getSendTime() {
		return this.sendTime;
	}

	public void setSendTime(Date sendTime) {
		this.sendTime = sendTime;
	}

	@Column(name = "apply_status", length = 32)
	public String getApplyStatus() {
		return this.applyStatus;
	}

	public void setApplyStatus(String applyStatus) {
		this.applyStatus = applyStatus;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "agree_time", length = 19)
	public Date getAgreeTime() {
		return this.agreeTime;
	}

	public void setAgreeTime(Date agreeTime) {
		this.agreeTime = agreeTime;
	}

}
