package org.sicdlab.entrepreneur.beans;
// Generated 2015-7-27 16:33:46 by Hibernate Tools 4.3.1

import java.util.Date;

/**
 * ProjectInstitution generated by hbm2java
 */
public class ProjectInstitution implements java.io.Serializable {

	private String id;
	private Institution institution;
	private Project project;
	private String content;
	private String applyType;
	private String title;
	private Date sendTime;
	private String applyStatus;
	private Date agreeTime;

	public ProjectInstitution() {
	}

	public ProjectInstitution(String id, Institution institution, Project project) {
		this.id = id;
		this.institution = institution;
		this.project = project;
	}

	public ProjectInstitution(String id, Institution institution, Project project, String content, String applyType,
			String title, Date sendTime, String applyStatus, Date agreeTime) {
		this.id = id;
		this.institution = institution;
		this.project = project;
		this.content = content;
		this.applyType = applyType;
		this.title = title;
		this.sendTime = sendTime;
		this.applyStatus = applyStatus;
		this.agreeTime = agreeTime;
	}

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public Institution getInstitution() {
		return this.institution;
	}

	public void setInstitution(Institution institution) {
		this.institution = institution;
	}

	public Project getProject() {
		return this.project;
	}

	public void setProject(Project project) {
		this.project = project;
	}

	public String getContent() {
		return this.content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	public String getApplyType() {
		return this.applyType;
	}

	public void setApplyType(String applyType) {
		this.applyType = applyType;
	}

	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public Date getSendTime() {
		return this.sendTime;
	}

	public void setSendTime(Date sendTime) {
		this.sendTime = sendTime;
	}

	public String getApplyStatus() {
		return this.applyStatus;
	}

	public void setApplyStatus(String applyStatus) {
		this.applyStatus = applyStatus;
	}

	public Date getAgreeTime() {
		return this.agreeTime;
	}

	public void setAgreeTime(Date agreeTime) {
		this.agreeTime = agreeTime;
	}

}
