package org.sicdlab.entrepreneur.beans;
// Generated 2015-8-5 16:28:47 by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * ProjectEntrepreneur generated by hbm2java
 */
@Entity
@Table(name = "project_entrepreneur", catalog = "entrepreneur_2015", uniqueConstraints = @UniqueConstraint(columnNames = "project_id") )
public class ProjectEntrepreneur implements java.io.Serializable {

	private String id;
	private Entrepreneur entrepreneur;
	private Project project;

	public ProjectEntrepreneur() {
	}

	public ProjectEntrepreneur(String id, Entrepreneur entrepreneur, Project project) {
		this.id = id;
		this.entrepreneur = entrepreneur;
		this.project = project;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false, length = 32)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "enterpreneur_id", nullable = false)
	public Entrepreneur getEntrepreneur() {
		return this.entrepreneur;
	}

	public void setEntrepreneur(Entrepreneur entrepreneur) {
		this.entrepreneur = entrepreneur;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "project_id", unique = true, nullable = false)
	public Project getProject() {
		return this.project;
	}

	public void setProject(Project project) {
		this.project = project;
	}

}
