package org.sicdlab.entrepreneur.beans;
// Generated 2015-7-27 16:33:46 by Hibernate Tools 4.3.1

/**
 * ProjectLabel generated by hbm2java
 */
public class ProjectLabel implements java.io.Serializable {

	private String id;
	private Label label;
	private Project project;

	public ProjectLabel() {
	}

	public ProjectLabel(String id, Label label, Project project) {
		this.id = id;
		this.label = label;
		this.project = project;
	}

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public Label getLabel() {
		return this.label;
	}

	public void setLabel(Label label) {
		this.label = label;
	}

	public Project getProject() {
		return this.project;
	}

	public void setProject(Project project) {
		this.project = project;
	}

}
