package org.sicdlab.entrepreneur.beans;
// Generated 2015-7-27 16:33:46 by Hibernate Tools 4.3.1

/**
 * ProjectEntrepreneur generated by hbm2java
 */
public class ProjectEntrepreneur implements java.io.Serializable {

	private String id;
	private Entrepreneur entrepreneur;
	private Project project;

	public ProjectEntrepreneur() {
	}

	public ProjectEntrepreneur(String id, Entrepreneur entrepreneur, Project project) {
		this.id = id;
		this.entrepreneur = entrepreneur;
		this.project = project;
	}

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public Entrepreneur getEntrepreneur() {
		return this.entrepreneur;
	}

	public void setEntrepreneur(Entrepreneur entrepreneur) {
		this.entrepreneur = entrepreneur;
	}

	public Project getProject() {
		return this.project;
	}

	public void setProject(Project project) {
		this.project = project;
	}

}
