package org.sicdlab.entrepreneur.beans;
// Generated 2015-7-27 16:33:46 by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Project generated by hbm2java
 */
public class Project implements java.io.Serializable {

	private String id;
	private Industry industry;
	private String name;
	private Date startTime;
	private String fundType;
	private BigDecimal fundAmountUpper;
	private BigDecimal fundAmountLower;
	private BigDecimal fundLackLower;
	private BigDecimal fundLackUpper;
	private String contact;
	private String introduce;
	private String area;
	private String managementStatus;
	private String projectStage;
	private Integer memberNumber;
	private Integer visitorNumber;
	private String projectStatus;
	private Set projectIndexes = new HashSet(0);
	private Set projectLabels = new HashSet(0);
	private Set projectInstitutions = new HashSet(0);
	private Set projectEntrepreneurs = new HashSet(0);
	private Set projectTutors = new HashSet(0);

	public Project() {
	}

	public Project(String id) {
		this.id = id;
	}

	public Project(String id, Industry industry, String name, Date startTime, String fundType,
			BigDecimal fundAmountUpper, BigDecimal fundAmountLower, BigDecimal fundLackLower, BigDecimal fundLackUpper,
			String contact, String introduce, String area, String managementStatus, String projectStage,
			Integer memberNumber, Integer visitorNumber, String projectStatus, Set projectIndexes, Set projectLabels,
			Set projectInstitutions, Set projectEntrepreneurs, Set projectTutors) {
		this.id = id;
		this.industry = industry;
		this.name = name;
		this.startTime = startTime;
		this.fundType = fundType;
		this.fundAmountUpper = fundAmountUpper;
		this.fundAmountLower = fundAmountLower;
		this.fundLackLower = fundLackLower;
		this.fundLackUpper = fundLackUpper;
		this.contact = contact;
		this.introduce = introduce;
		this.area = area;
		this.managementStatus = managementStatus;
		this.projectStage = projectStage;
		this.memberNumber = memberNumber;
		this.visitorNumber = visitorNumber;
		this.projectStatus = projectStatus;
		this.projectIndexes = projectIndexes;
		this.projectLabels = projectLabels;
		this.projectInstitutions = projectInstitutions;
		this.projectEntrepreneurs = projectEntrepreneurs;
		this.projectTutors = projectTutors;
	}

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public Industry getIndustry() {
		return this.industry;
	}

	public void setIndustry(Industry industry) {
		this.industry = industry;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Date getStartTime() {
		return this.startTime;
	}

	public void setStartTime(Date startTime) {
		this.startTime = startTime;
	}

	public String getFundType() {
		return this.fundType;
	}

	public void setFundType(String fundType) {
		this.fundType = fundType;
	}

	public BigDecimal getFundAmountUpper() {
		return this.fundAmountUpper;
	}

	public void setFundAmountUpper(BigDecimal fundAmountUpper) {
		this.fundAmountUpper = fundAmountUpper;
	}

	public BigDecimal getFundAmountLower() {
		return this.fundAmountLower;
	}

	public void setFundAmountLower(BigDecimal fundAmountLower) {
		this.fundAmountLower = fundAmountLower;
	}

	public BigDecimal getFundLackLower() {
		return this.fundLackLower;
	}

	public void setFundLackLower(BigDecimal fundLackLower) {
		this.fundLackLower = fundLackLower;
	}

	public BigDecimal getFundLackUpper() {
		return this.fundLackUpper;
	}

	public void setFundLackUpper(BigDecimal fundLackUpper) {
		this.fundLackUpper = fundLackUpper;
	}

	public String getContact() {
		return this.contact;
	}

	public void setContact(String contact) {
		this.contact = contact;
	}

	public String getIntroduce() {
		return this.introduce;
	}

	public void setIntroduce(String introduce) {
		this.introduce = introduce;
	}

	public String getArea() {
		return this.area;
	}

	public void setArea(String area) {
		this.area = area;
	}

	public String getManagementStatus() {
		return this.managementStatus;
	}

	public void setManagementStatus(String managementStatus) {
		this.managementStatus = managementStatus;
	}

	public String getProjectStage() {
		return this.projectStage;
	}

	public void setProjectStage(String projectStage) {
		this.projectStage = projectStage;
	}

	public Integer getMemberNumber() {
		return this.memberNumber;
	}

	public void setMemberNumber(Integer memberNumber) {
		this.memberNumber = memberNumber;
	}

	public Integer getVisitorNumber() {
		return this.visitorNumber;
	}

	public void setVisitorNumber(Integer visitorNumber) {
		this.visitorNumber = visitorNumber;
	}

	public String getProjectStatus() {
		return this.projectStatus;
	}

	public void setProjectStatus(String projectStatus) {
		this.projectStatus = projectStatus;
	}

	public Set getProjectIndexes() {
		return this.projectIndexes;
	}

	public void setProjectIndexes(Set projectIndexes) {
		this.projectIndexes = projectIndexes;
	}

	public Set getProjectLabels() {
		return this.projectLabels;
	}

	public void setProjectLabels(Set projectLabels) {
		this.projectLabels = projectLabels;
	}

	public Set getProjectInstitutions() {
		return this.projectInstitutions;
	}

	public void setProjectInstitutions(Set projectInstitutions) {
		this.projectInstitutions = projectInstitutions;
	}

	public Set getProjectEntrepreneurs() {
		return this.projectEntrepreneurs;
	}

	public void setProjectEntrepreneurs(Set projectEntrepreneurs) {
		this.projectEntrepreneurs = projectEntrepreneurs;
	}

	public Set getProjectTutors() {
		return this.projectTutors;
	}

	public void setProjectTutors(Set projectTutors) {
		this.projectTutors = projectTutors;
	}

}
