package org.sicdlab.entrepreneur.beans;
// Generated 2015-7-27 16:33:46 by Hibernate Tools 4.3.1

/**
 * Resource generated by hbm2java
 */
public class Resource implements java.io.Serializable {

	private String id;
	private String ownerId;
	private String resourceType;
	private String status;
	private String path;

	public Resource() {
	}

	public Resource(String id) {
		this.id = id;
	}

	public Resource(String id, String ownerId, String resourceType, String status, String path) {
		this.id = id;
		this.ownerId = ownerId;
		this.resourceType = resourceType;
		this.status = status;
		this.path = path;
	}

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getOwnerId() {
		return this.ownerId;
	}

	public void setOwnerId(String ownerId) {
		this.ownerId = ownerId;
	}

	public String getResourceType() {
		return this.resourceType;
	}

	public void setResourceType(String resourceType) {
		this.resourceType = resourceType;
	}

	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public String getPath() {
		return this.path;
	}

	public void setPath(String path) {
		this.path = path;
	}

}
