package org.sicdlab.entrepreneur.beans;
// Generated 2015-7-27 16:33:46 by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

/**
 * Role generated by hbm2java
 */
public class Role implements java.io.Serializable {

	private String id;
	private String name;
	private Set users = new HashSet(0);
	private Set roleAuthorities = new HashSet(0);

	public Role() {
	}

	public Role(String id, String name) {
		this.id = id;
		this.name = name;
	}

	public Role(String id, String name, Set users, Set roleAuthorities) {
		this.id = id;
		this.name = name;
		this.users = users;
		this.roleAuthorities = roleAuthorities;
	}

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Set getUsers() {
		return this.users;
	}

	public void setUsers(Set users) {
		this.users = users;
	}

	public Set getRoleAuthorities() {
		return this.roleAuthorities;
	}

	public void setRoleAuthorities(Set roleAuthorities) {
		this.roleAuthorities = roleAuthorities;
	}

}
