package org.sicdlab.entrepreneur.beans;
// Generated 2015-7-27 16:33:46 by Hibernate Tools 4.3.1

/**
 * RoleAuthority generated by hbm2java
 */
public class RoleAuthority implements java.io.Serializable {

	private String id;
	private Authority authority;
	private Role role;

	public RoleAuthority() {
	}

	public RoleAuthority(String id, Authority authority, Role role) {
		this.id = id;
		this.authority = authority;
		this.role = role;
	}

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public Authority getAuthority() {
		return this.authority;
	}

	public void setAuthority(Authority authority) {
		this.authority = authority;
	}

	public Role getRole() {
		return this.role;
	}

	public void setRole(Role role) {
		this.role = role;
	}

}
