package org.sicdlab.entrepreneur.beans;
// Generated 2015-7-27 16:33:46 by Hibernate Tools 4.3.1

/**
 * SupplyLabel generated by hbm2java
 */
public class SupplyLabel implements java.io.Serializable {

	private String id;
	private Label label;
	private Supply supply;

	public SupplyLabel() {
	}

	public SupplyLabel(String id, Label label, Supply supply) {
		this.id = id;
		this.label = label;
		this.supply = supply;
	}

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public Label getLabel() {
		return this.label;
	}

	public void setLabel(Label label) {
		this.label = label;
	}

	public Supply getSupply() {
		return this.supply;
	}

	public void setSupply(Supply supply) {
		this.supply = supply;
	}

}
