package org.sicdlab.entrepreneur.beans;
// Generated 2015-7-27 16:33:46 by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Supply generated by hbm2java
 */
public class Supply implements java.io.Serializable {

	private String id;
	private Industry industry;
	private User user;
	private String title;
	private String type;
	private String content;
	private Date publishTime;
	private String email;
	private String contact;
	private String area;
	private String fundAmount;
	private Set supplyLabels = new HashSet(0);

	public Supply() {
	}

	public Supply(String id, User user, String title, String type, Date publishTime) {
		this.id = id;
		this.user = user;
		this.title = title;
		this.type = type;
		this.publishTime = publishTime;
	}

	public Supply(String id, Industry industry, User user, String title, String type, String content, Date publishTime,
			String email, String contact, String area, String fundAmount, Set supplyLabels) {
		this.id = id;
		this.industry = industry;
		this.user = user;
		this.title = title;
		this.type = type;
		this.content = content;
		this.publishTime = publishTime;
		this.email = email;
		this.contact = contact;
		this.area = area;
		this.fundAmount = fundAmount;
		this.supplyLabels = supplyLabels;
	}

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public Industry getIndustry() {
		return this.industry;
	}

	public void setIndustry(Industry industry) {
		this.industry = industry;
	}

	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	public String getContent() {
		return this.content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	public Date getPublishTime() {
		return this.publishTime;
	}

	public void setPublishTime(Date publishTime) {
		this.publishTime = publishTime;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getContact() {
		return this.contact;
	}

	public void setContact(String contact) {
		this.contact = contact;
	}

	public String getArea() {
		return this.area;
	}

	public void setArea(String area) {
		this.area = area;
	}

	public String getFundAmount() {
		return this.fundAmount;
	}

	public void setFundAmount(String fundAmount) {
		this.fundAmount = fundAmount;
	}

	public Set getSupplyLabels() {
		return this.supplyLabels;
	}

	public void setSupplyLabels(Set supplyLabels) {
		this.supplyLabels = supplyLabels;
	}

}
