package org.sicdlab.entrepreneur.beans;
// Generated 2015-8-5 16:28:47 by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Supply generated by hbm2java
 */
@Entity
@Table(name = "supply", catalog = "entrepreneur_2015")
public class Supply implements java.io.Serializable {

	private String id;
	private Industry industry;
	private User user;
	private String title;
	private String type;
	private String content;
	private Date publishTime;
	private String email;
	private String contact;
	private String area;
	private String fundAmount;
	private Set supplyLabels = new HashSet(0);

	public Supply() {
	}

	public Supply(String id, User user, String title, String type, Date publishTime) {
		this.id = id;
		this.user = user;
		this.title = title;
		this.type = type;
		this.publishTime = publishTime;
	}

	public Supply(String id, Industry industry, User user, String title, String type, String content, Date publishTime, String email, String contact, String area,
			String fundAmount, Set supplyLabels) {
		this.id = id;
		this.industry = industry;
		this.user = user;
		this.title = title;
		this.type = type;
		this.content = content;
		this.publishTime = publishTime;
		this.email = email;
		this.contact = contact;
		this.area = area;
		this.fundAmount = fundAmount;
		this.supplyLabels = supplyLabels;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false, length = 32)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "industry_id")
	public Industry getIndustry() {
		return this.industry;
	}

	public void setIndustry(Industry industry) {
		this.industry = industry;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "user_id", nullable = false)
	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	@Column(name = "title", nullable = false, length = 200)
	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	@Column(name = "type", nullable = false, length = 50)
	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	@Column(name = "content", length = 65535)
	public String getContent() {
		return this.content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "publish_time", nullable = false, length = 19)
	public Date getPublishTime() {
		return this.publishTime;
	}

	public void setPublishTime(Date publishTime) {
		this.publishTime = publishTime;
	}

	@Column(name = "email", length = 50)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "contact", length = 50)
	public String getContact() {
		return this.contact;
	}

	public void setContact(String contact) {
		this.contact = contact;
	}

	@Column(name = "area", length = 50)
	public String getArea() {
		return this.area;
	}

	public void setArea(String area) {
		this.area = area;
	}

	@Column(name = "fund_amount", length = 32)
	public String getFundAmount() {
		return this.fundAmount;
	}

	public void setFundAmount(String fundAmount) {
		this.fundAmount = fundAmount;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "supply")
	public Set getSupplyLabels() {
		return this.supplyLabels;
	}

	public void setSupplyLabels(Set supplyLabels) {
		this.supplyLabels = supplyLabels;
	}

}
