package org.sicdlab.entrepreneur.beans;
// Generated 2015-7-27 16:33:46 by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

/**
 * TeamCoreCompetence generated by hbm2java
 */
public class TeamCoreCompetence implements java.io.Serializable {

	private String teamCoreCompetenceId;
	private float teamEntrepreneurshipExperience;
	private float teamProfessionSkill;
	private float teamHomogeneity;
	private float teamMemberFamiliarDegree;
	private float totalScore;
	private String comment;
	private Set managementTeams = new HashSet(0);

	public TeamCoreCompetence() {
	}

	public TeamCoreCompetence(String teamCoreCompetenceId, float teamEntrepreneurshipExperience,
			float teamProfessionSkill, float teamHomogeneity, float teamMemberFamiliarDegree, float totalScore) {
		this.teamCoreCompetenceId = teamCoreCompetenceId;
		this.teamEntrepreneurshipExperience = teamEntrepreneurshipExperience;
		this.teamProfessionSkill = teamProfessionSkill;
		this.teamHomogeneity = teamHomogeneity;
		this.teamMemberFamiliarDegree = teamMemberFamiliarDegree;
		this.totalScore = totalScore;
	}

	public TeamCoreCompetence(String teamCoreCompetenceId, float teamEntrepreneurshipExperience,
			float teamProfessionSkill, float teamHomogeneity, float teamMemberFamiliarDegree, float totalScore,
			String comment, Set managementTeams) {
		this.teamCoreCompetenceId = teamCoreCompetenceId;
		this.teamEntrepreneurshipExperience = teamEntrepreneurshipExperience;
		this.teamProfessionSkill = teamProfessionSkill;
		this.teamHomogeneity = teamHomogeneity;
		this.teamMemberFamiliarDegree = teamMemberFamiliarDegree;
		this.totalScore = totalScore;
		this.comment = comment;
		this.managementTeams = managementTeams;
	}

	public String getTeamCoreCompetenceId() {
		return this.teamCoreCompetenceId;
	}

	public void setTeamCoreCompetenceId(String teamCoreCompetenceId) {
		this.teamCoreCompetenceId = teamCoreCompetenceId;
	}

	public float getTeamEntrepreneurshipExperience() {
		return this.teamEntrepreneurshipExperience;
	}

	public void setTeamEntrepreneurshipExperience(float teamEntrepreneurshipExperience) {
		this.teamEntrepreneurshipExperience = teamEntrepreneurshipExperience;
	}

	public float getTeamProfessionSkill() {
		return this.teamProfessionSkill;
	}

	public void setTeamProfessionSkill(float teamProfessionSkill) {
		this.teamProfessionSkill = teamProfessionSkill;
	}

	public float getTeamHomogeneity() {
		return this.teamHomogeneity;
	}

	public void setTeamHomogeneity(float teamHomogeneity) {
		this.teamHomogeneity = teamHomogeneity;
	}

	public float getTeamMemberFamiliarDegree() {
		return this.teamMemberFamiliarDegree;
	}

	public void setTeamMemberFamiliarDegree(float teamMemberFamiliarDegree) {
		this.teamMemberFamiliarDegree = teamMemberFamiliarDegree;
	}

	public float getTotalScore() {
		return this.totalScore;
	}

	public void setTotalScore(float totalScore) {
		this.totalScore = totalScore;
	}

	public String getComment() {
		return this.comment;
	}

	public void setComment(String comment) {
		this.comment = comment;
	}

	public Set getManagementTeams() {
		return this.managementTeams;
	}

	public void setManagementTeams(Set managementTeams) {
		this.managementTeams = managementTeams;
	}

}
