package org.sicdlab.entrepreneur.beans;
// Generated 2015-8-5 16:28:47 by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TeamCoreCompetence generated by hbm2java
 */
@Entity
@Table(name = "team_core_competence", catalog = "entrepreneur_2015")
public class TeamCoreCompetence implements java.io.Serializable {

	private String teamCoreCompetenceId;
	private float teamEntrepreneurshipExperience;
	private float teamProfessionSkill;
	private float teamHomogeneity;
	private float teamMemberFamiliarDegree;
	private float totalScore;
	private String comment;
	private Set managementTeams = new HashSet(0);

	public TeamCoreCompetence() {
	}

	public TeamCoreCompetence(String teamCoreCompetenceId, float teamEntrepreneurshipExperience, float teamProfessionSkill, float teamHomogeneity,
			float teamMemberFamiliarDegree, float totalScore) {
		this.teamCoreCompetenceId = teamCoreCompetenceId;
		this.teamEntrepreneurshipExperience = teamEntrepreneurshipExperience;
		this.teamProfessionSkill = teamProfessionSkill;
		this.teamHomogeneity = teamHomogeneity;
		this.teamMemberFamiliarDegree = teamMemberFamiliarDegree;
		this.totalScore = totalScore;
	}

	public TeamCoreCompetence(String teamCoreCompetenceId, float teamEntrepreneurshipExperience, float teamProfessionSkill, float teamHomogeneity,
			float teamMemberFamiliarDegree, float totalScore, String comment, Set managementTeams) {
		this.teamCoreCompetenceId = teamCoreCompetenceId;
		this.teamEntrepreneurshipExperience = teamEntrepreneurshipExperience;
		this.teamProfessionSkill = teamProfessionSkill;
		this.teamHomogeneity = teamHomogeneity;
		this.teamMemberFamiliarDegree = teamMemberFamiliarDegree;
		this.totalScore = totalScore;
		this.comment = comment;
		this.managementTeams = managementTeams;
	}

	@Id

	@Column(name = "TEAM_CORE_COMPETENCE_ID", unique = true, nullable = false, length = 32)
	public String getTeamCoreCompetenceId() {
		return this.teamCoreCompetenceId;
	}

	public void setTeamCoreCompetenceId(String teamCoreCompetenceId) {
		this.teamCoreCompetenceId = teamCoreCompetenceId;
	}

	@Column(name = "TEAM_ENTREPRENEURSHIP_EXPERIENCE", nullable = false, precision = 10)
	public float getTeamEntrepreneurshipExperience() {
		return this.teamEntrepreneurshipExperience;
	}

	public void setTeamEntrepreneurshipExperience(float teamEntrepreneurshipExperience) {
		this.teamEntrepreneurshipExperience = teamEntrepreneurshipExperience;
	}

	@Column(name = "TEAM_PROFESSION_SKILL", nullable = false, precision = 10)
	public float getTeamProfessionSkill() {
		return this.teamProfessionSkill;
	}

	public void setTeamProfessionSkill(float teamProfessionSkill) {
		this.teamProfessionSkill = teamProfessionSkill;
	}

	@Column(name = "TEAM_HOMOGENEITY", nullable = false, precision = 10)
	public float getTeamHomogeneity() {
		return this.teamHomogeneity;
	}

	public void setTeamHomogeneity(float teamHomogeneity) {
		this.teamHomogeneity = teamHomogeneity;
	}

	@Column(name = "TEAM_MEMBER_FAMILIAR_DEGREE", nullable = false, precision = 10)
	public float getTeamMemberFamiliarDegree() {
		return this.teamMemberFamiliarDegree;
	}

	public void setTeamMemberFamiliarDegree(float teamMemberFamiliarDegree) {
		this.teamMemberFamiliarDegree = teamMemberFamiliarDegree;
	}

	@Column(name = "TOTAL_SCORE", nullable = false, precision = 10)
	public float getTotalScore() {
		return this.totalScore;
	}

	public void setTotalScore(float totalScore) {
		this.totalScore = totalScore;
	}

	@Column(name = "COMMENT", length = 65535)
	public String getComment() {
		return this.comment;
	}

	public void setComment(String comment) {
		this.comment = comment;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "teamCoreCompetence")
	public Set getManagementTeams() {
		return this.managementTeams;
	}

	public void setManagementTeams(Set managementTeams) {
		this.managementTeams = managementTeams;
	}

}
