package org.sicdlab.entrepreneur.beans;
// Generated 2015-8-5 16:28:47 by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * Tutor generated by hbm2java
 */
@Entity
@Table(name = "tutor", catalog = "entrepreneur_2015")
public class Tutor implements java.io.Serializable {

	private String id;
	private User user;
	private String type;
	private String experience;
	private String occupation;
	private String tutorship;
	private Float averageScore;
	private Set projectTutors = new HashSet(0);

	public Tutor() {
	}

	public Tutor(User user) {
		this.user = user;
	}

	public Tutor(User user, String type, String experience, String occupation, String tutorship, Float averageScore, Set projectTutors) {
		this.user = user;
		this.type = type;
		this.experience = experience;
		this.occupation = occupation;
		this.tutorship = tutorship;
		this.averageScore = averageScore;
		this.projectTutors = projectTutors;
	}

	@GenericGenerator(name = "generator", strategy = "foreign", parameters = @Parameter(name = "property", value = "user") )
	@Id
	@GeneratedValue(generator = "generator")

	@Column(name = "id", unique = true, nullable = false, length = 32)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@OneToOne(fetch = FetchType.LAZY)
	@PrimaryKeyJoinColumn
	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	@Column(name = "type", length = 32)
	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	@Column(name = "experience", length = 65535)
	public String getExperience() {
		return this.experience;
	}

	public void setExperience(String experience) {
		this.experience = experience;
	}

	@Column(name = "occupation", length = 200)
	public String getOccupation() {
		return this.occupation;
	}

	public void setOccupation(String occupation) {
		this.occupation = occupation;
	}

	@Column(name = "tutorship", length = 200)
	public String getTutorship() {
		return this.tutorship;
	}

	public void setTutorship(String tutorship) {
		this.tutorship = tutorship;
	}

	@Column(name = "average_score", precision = 32, scale = 0)
	public Float getAverageScore() {
		return this.averageScore;
	}

	public void setAverageScore(Float averageScore) {
		this.averageScore = averageScore;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tutor")
	public Set getProjectTutors() {
		return this.projectTutors;
	}

	public void setProjectTutors(Set projectTutors) {
		this.projectTutors = projectTutors;
	}

}
