package org.sicdlab.entrepreneur.beans;
// Generated 2015-7-27 16:33:46 by Hibernate Tools 4.3.1

/**
 * UserLabel generated by hbm2java
 */
public class UserLabel implements java.io.Serializable {

	private String id;
	private User user;
	private String labelId;

	public UserLabel() {
	}

	public UserLabel(String id, User user, String labelId) {
		this.id = id;
		this.user = user;
		this.labelId = labelId;
	}

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	public String getLabelId() {
		return this.labelId;
	}

	public void setLabelId(String labelId) {
		this.labelId = labelId;
	}

}
